window.QB = window.QB || {};

/* ============================================================
   NAPLAN SPELLING  –  60 questions  (20Q / test)
   Year 2 warm-up level | Victorian Curriculum VCELA / VCELY
   Format: sentence with a gap; student picks correct spelling.
   ============================================================ */
window.QB.naplan_spell = [

  /* ── CVC & Common Short Words ── */
  {id:'sp01',q:'Choose the correct spelling to complete the sentence:\n"The ___ ran across the road."',
   o:['rabet','rabbit','rabit','rabbitt'],a:1,t:'Spelling',e:'"Rabbit" — double b, ends in -it.'},
  {id:'sp02',q:'Choose the correct spelling:\n"We went to the ___ to buy food."',
   o:['markit','market','marcket','markett'],a:1,t:'Spelling',e:'"Market" — mar-ket.'},
  {id:'sp03',q:'Choose the correct spelling:\n"The ___ was very tall."',
   o:['tree','trea','trei','tre'],a:0,t:'Spelling',e:'"Tree" — tr-ee. Double e at the end.'},
  {id:'sp04',q:'Choose the correct spelling:\n"She wore a ___ dress."',
   o:['byootiful','beautiful','beautifull','beutiful'],a:1,t:'Spelling',e:'"Beautiful" — beau-ti-ful.'},
  {id:'sp05',q:'Choose the correct spelling:\n"He sat on the ___ to watch TV."',
   o:['sofa','sopha','sofah','sophar'],a:0,t:'Spelling',e:'"Sofa" — so-fa.'},
  {id:'sp06',q:'Choose the correct spelling:\n"The ___ was barking loudly."',
   o:['dawg','dogg','dog','dogue'],a:2,t:'Spelling',e:'"Dog" — simple three-letter word.'},
  {id:'sp07',q:'Choose the correct spelling:\n"It was a ___ day in Melbourne."',
   o:['sunnny','sunny','sunni','sunney'],a:1,t:'Spelling',e:'"Sunny" — sun + ny (double n).'},
  {id:'sp08',q:'Choose the correct spelling:\n"The ___ is my favourite sport."',
   o:['cricket','criket','crikket','crickett'],a:0,t:'Spelling',e:'"Cricket" — cric-ket.'},

  /* ── Blends & Digraphs ── */
  {id:'sp09',q:'Choose the correct spelling:\n"She put on her ___ before going outside."',
   o:['shoz','shoez','shoes','shooes'],a:2,t:'Spelling',e:'"Shoes" — shoe + s.'},
  {id:'sp10',q:'Choose the correct spelling:\n"The ___ was loud during the storm."',
   o:['thander','thunderr','thunder','thundar'],a:2,t:'Spelling',e:'"Thunder" — th-un-der.'},
  {id:'sp11',q:'Choose the correct spelling:\n"I like to ___ at the park."',
   o:['swwing','swing','suing','sweng'],a:1,t:'Spelling',e:'"Swing" — sw-ing.'},
  {id:'sp12',q:'Choose the correct spelling:\n"She drew a ___ on her notebook."',
   o:['flouwer','flower','flouer','flowwer'],a:1,t:'Spelling',e:'"Flower" — fl-ow-er.'},
  {id:'sp13',q:'Choose the correct spelling:\n"The ___ flew high in the sky."',
   o:['butterflye','butterfly','butterflie','butterfligh'],a:1,t:'Spelling',e:'"Butterfly" — but-ter-fly.'},
  {id:'sp14',q:'Choose the correct spelling:\n"We played ___ after school."',
   o:['foosball','football','futball','footbal'],a:1,t:'Spelling',e:'"Football" — foot + ball.'},
  {id:'sp15',q:'Choose the correct spelling:\n"She wrapped a ___ around her neck."',
   o:['scarf','scaarf','scarfe','skarf'],a:0,t:'Spelling',e:'"Scarf" — sc-ar-f.'},

  /* ── Long Vowel Patterns ── */
  {id:'sp16',q:'Choose the correct spelling:\n"The ___ shone all day."',
   o:['sun','son','sune','sunn'],a:0,t:'Spelling',e:'"Sun" — simple three-letter word with short u.'},
  {id:'sp17',q:'Choose the correct spelling:\n"He rode his ___ to school."',
   o:['bike','biek','byke','biike'],a:0,t:'Spelling',e:'"Bike" — b-i-k-e (silent e makes the i long).'},
  {id:'sp18',q:'Choose the correct spelling:\n"She ate a ___ for lunch."',
   o:['caike','cake','caak','cayk'],a:1,t:'Spelling',e:'"Cake" — c-a-k-e. Silent e at the end.'},
  {id:'sp19',q:'Choose the correct spelling:\n"The ___ is a large animal."',
   o:['whail','wale','whale','whalle'],a:2,t:'Spelling',e:'"Whale" — wh-a-l-e. Silent wh at the start.'},
  {id:'sp20',q:'Choose the correct spelling:\n"We saw a ___ in the ocean."',
   o:['shrak','sharc','sharkk','shark'],a:3,t:'Spelling',e:'"Shark" — sh-ar-k.'},

  /* ── Common Tricky Words ── */
  {id:'sp21',q:'Choose the correct spelling:\n"She has ___ apples."',
   o:['eight','eigt','ait','eihgt'],a:0,t:'Spelling',e:'"Eight" — the tricky -ight ending. e-i-g-h-t.'},
  {id:'sp22',q:'Choose the correct spelling:\n"He ___ to school every day."',
   o:['walkes','walks','walkes','walkz'],a:1,t:'Spelling',e:'"Walks" — walk + s.'},
  {id:'sp23',q:'Choose the correct spelling:\n"The ___ is our classroom helper."',
   o:['teaher','teacher','techer','teachar'],a:1,t:'Spelling',e:'"Teacher" — teach + er.'},
  {id:'sp24',q:'Choose the correct spelling:\n"She ___ a letter to her friend."',
   o:['rote','wrote','rite','wroat'],a:1,t:'Spelling',e:'"Wrote" — wr-o-t-e. Silent w at the start.'},
  {id:'sp25',q:'Choose the correct spelling:\n"The ___ at the zoo was funny."',
   o:['munkee','monkey','monkee','monky'],a:1,t:'Spelling',e:'"Monkey" — mon-key.'},
  {id:'sp26',q:'Choose the correct spelling:\n"___ are you going?"',
   o:['Wair','Wher','Wear','Where'],a:3,t:'Spelling',e:'"Where" — wh-e-r-e. Where asks about a place.'},
  {id:'sp27',q:'Choose the correct spelling:\n"They brought ___ own lunches."',
   o:['there','their','they\'re','thare'],a:1,t:'Spelling',e:'"Their" shows belonging — their own lunches.'},
  {id:'sp28',q:'Choose the correct spelling:\n"He could not ___ the music."',
   o:['heer','hear','hair','here'],a:1,t:'Spelling',e:'"Hear" — h-e-a-r. You use your ear to hear.'},

  /* ── Suffixes & Plurals ── */
  {id:'sp29',q:'Choose the correct spelling:\n"There are three ___ in the garden."',
   o:['butterflys','butterflies','butterfles','butterfly\'s'],a:1,t:'Spelling',
   e:'"Butterflies" — words ending in y change to -ies for the plural.'},
  {id:'sp30',q:'Choose the correct spelling:\n"She was ___ when she won the prize."',
   o:['happi','happyy','happy','hapi'],a:2,t:'Spelling',e:'"Happy" — hap-py, double p.'},
  {id:'sp31',q:'Choose the correct spelling:\n"The ___ were playing in the yard."',
   o:['childrens','children','childrun','childre'],a:1,t:'Spelling',e:'"Children" — irregular plural of child.'},
  {id:'sp32',q:'Choose the correct spelling:\n"The ___ were barking all night."',
   o:['dogs','doges','dogges','doge'],a:0,t:'Spelling',e:'"Dogs" — simple plural, add s.'},
  {id:'sp33',q:'Choose the correct spelling:\n"He is ___ his homework."',
   o:['doeing','doing','dueing','duing'],a:1,t:'Spelling',e:'"Doing" — do + ing. Drop the e and add -ing? No, do + ing = doing.'},
  {id:'sp34',q:'Choose the correct spelling:\n"She is ___ a story."',
   o:['writeing','writting','writing','writhing'],a:2,t:'Spelling',e:'"Writing" — write → drop the e → writing.'},
  {id:'sp35',q:'Choose the correct spelling:\n"The ___ are playing cricket."',
   o:['boys','boyes','boies','boyz'],a:0,t:'Spelling',e:'"Boys" — simple plural, add s.'},
  {id:'sp36',q:'Choose the correct spelling:\n"It was the ___ day of school."',
   o:['furst','ferst','first','frist'],a:2,t:'Spelling',e:'"First" — fir-st.'},

  /* ── High-frequency Academic Words ── */
  {id:'sp37',q:'Choose the correct spelling:\n"The ___ of the story was about friendship."',
   o:['messij','mesage','message','massage'],a:2,t:'Spelling',e:'"Message" — mes-sage.'},
  {id:'sp38',q:'Choose the correct spelling:\n"She gave the correct ___."',
   o:['anser','ansure','answer','answr'],a:2,t:'Spelling',e:'"Answer" — ans-wer. The w is silent in speech.'},
  {id:'sp39',q:'Choose the correct spelling:\n"The ___ was very exciting."',
   o:['adventuure','adventure','adventur','advenchure'],a:1,t:'Spelling',e:'"Adventure" — ad-ven-ture.'},
  {id:'sp40',q:'Choose the correct spelling:\n"We need to ___ who wins."',
   o:['desied','dicied','deside','decide'],a:3,t:'Spelling',e:'"Decide" — de-cide.'},
  {id:'sp41',q:'Choose the correct spelling:\n"He was ___ with the result."',
   o:['pleased','pleesed','plaesed','pleesd'],a:0,t:'Spelling',e:'"Pleased" — please + d.'},
  {id:'sp42',q:'Choose the correct spelling:\n"She had a ___ smile on her face."',
   o:['brite','bright','briht','brigt'],a:1,t:'Spelling',e:'"Bright" — br-ight. The -ight pattern.'},
  {id:'sp43',q:'Choose the correct spelling:\n"The ___ of Australia is Canberra."',
   o:['capitul','capital','capittle','capitall'],a:1,t:'Spelling',e:'"Capital" — cap-i-tal.'},
  {id:'sp44',q:'Choose the correct spelling:\n"He felt ___ before the big test."',
   o:['nervus','nervious','nervous','nervuos'],a:2,t:'Spelling',e:'"Nervous" — ner-vous.'},
  {id:'sp45',q:'Choose the correct spelling:\n"They live in a ___ near the park."',
   o:['nighbourhood','neighborhood','neighbourhood','neighburhood'],a:2,t:'Spelling',
   e:'"Neighbourhood" — neigh-bour-hood. Australian spelling uses -our.'},
  {id:'sp46',q:'Choose the correct spelling:\n"She loves to ___ books about animals."',
   o:['reed','read','rede','raed'],a:1,t:'Spelling',e:'"Read" — r-e-a-d.'},
  {id:'sp47',q:'Choose the correct spelling:\n"He ___ his bike to the park."',
   o:['rided','rode','roaded','rid'],a:1,t:'Spelling',e:'"Rode" — past tense of ride.'},
  {id:'sp48',q:'Choose the correct spelling:\n"The ___ had colourful feathers."',
   o:['parrit','parrot','parott','parott'],a:1,t:'Spelling',e:'"Parrot" — par-rot. Double r.'},
  {id:'sp49',q:'Choose the correct spelling:\n"We went on a ___ to the museum."',
   o:['excursion','excurshun','excursean','excurtion'],a:0,t:'Spelling',e:'"Excursion" — ex-cur-sion.'},
  {id:'sp50',q:'Choose the correct spelling:\n"The ___ was delicious."',
   o:['biscut','biscutt','biscuit','bisquit'],a:2,t:'Spelling',e:'"Biscuit" — bis-cuit. The ui makes an "i" sound.'},
  {id:'sp51',q:'Choose the correct spelling:\n"She felt very ___."',
   o:['tired','tiyered','tirred','tyred'],a:0,t:'Spelling',e:'"Tired" — tire + d.'},
  {id:'sp52',q:'Choose the correct spelling:\n"The ___ is a native Australian bird."',
   o:['kookaburra','kukkaburra','kookaburrah','kukaburra'],a:0,t:'Spelling',e:'"Kookaburra" — koo-ka-bur-ra.'},
  {id:'sp53',q:'Choose the correct spelling:\n"He ___ the ball into the net."',
   o:['kicked','kict','kikked','kiked'],a:0,t:'Spelling',e:'"Kicked" — kick + ed.'},
  {id:'sp54',q:'Choose the correct spelling:\n"She was feeling very ___."',
   o:['ekscited','exsited','exited','excited'],a:3,t:'Spelling',e:'"Excited" — ex-cit-ed.'},
  {id:'sp55',q:'Choose the correct spelling:\n"The ___ was very interesting."',
   o:['libraree','library','librery','libary'],a:1,t:'Spelling',e:'"Library" — li-brar-y.'},
  {id:'sp56',q:'Choose the correct spelling:\n"We planted ___ in the garden."',
   o:['vegetabels','vegetables','vegitables','vegitabls'],a:1,t:'Spelling',e:'"Vegetables" — veg-e-ta-bles.'},
  {id:'sp57',q:'Choose the correct spelling:\n"The sky was ___ with clouds."',
   o:['covered','coverd','covared','covured'],a:0,t:'Spelling',e:'"Covered" — cover + ed.'},
  {id:'sp58',q:'Choose the correct spelling:\n"We had a ___ time at the carnival."',
   o:['wonderfull','wunderful','wonderful','wondirful'],a:2,t:'Spelling',e:'"Wonderful" — won-der-ful.'},
  {id:'sp59',q:'Choose the correct spelling:\n"She lives in ___."',
   o:['Melburn','Melbourn','Melbourne','Melberne'],a:2,t:'Spelling',e:'"Melbourne" — Mel-bourne. Australian city.'},
  {id:'sp60',q:'Choose the correct spelling:\n"He ___ his name on the paper."',
   o:['writed','rote','wrote','wroate'],a:2,t:'Spelling',e:'"Wrote" — past tense of write. Silent w.'}
];

/* ============================================================
   NAPLAN GRAMMAR & PUNCTUATION  –  62 questions  (20Q / test)
   Year 2 warm-up level | Victorian Curriculum VCELA / VCELY
   ============================================================ */
window.QB.naplan_gram = [

  /* ── Nouns ── */
  {id:'g01',q:'Which word is a noun (naming word) in the sentence: "The dog chased the ball."?',
   o:['chased','the','quickly','dog'],a:3,t:'Nouns',e:'"Dog" is a noun — it names a thing (an animal).'},
  {id:'g02',q:'Which of these is a proper noun?',
   o:['city','river','Melbourne','park'],a:2,t:'Nouns',
   e:'"Melbourne" is a proper noun — it names a specific place and starts with a capital letter.'},
  {id:'g03',q:'Choose the correct plural:\n"There are three ___ in the tree." (bush)',
   o:['bushs','bushes','bushy','bush\'s'],a:1,t:'Nouns',e:'Words ending in -sh get -es added: bush → bushes.'},
  {id:'g04',q:'What is the plural of "child"?',
   o:['childs','childes','children','childrens'],a:2,t:'Nouns',e:'"Children" is the irregular plural of child.'},
  {id:'g05',q:'Which sentence uses a collective noun correctly?',
   o:['A pack of wolves ran past.','A wolves of pack ran past.','A ran of wolves pack past.','Pack a wolves of ran past.'],
   a:0,t:'Nouns',e:'"A pack of wolves" — "pack" is the collective noun for a group of wolves.'},

  /* ── Verbs ── */
  {id:'g06',q:'Which word is the verb (doing word) in: "She quickly ran to school."?',
   o:['quickly','she','school','ran'],a:3,t:'Verbs',e:'"Ran" is the verb — it describes the action (running).'},
  {id:'g07',q:'Choose the correct verb form:\n"Yesterday, she ___ to school."',
   o:['walk','walks','walked','is walking'],a:2,t:'Verbs',
   e:'"Walked" — yesterday signals past tense, so we use the past tense form.'},
  {id:'g08',q:'Which sentence is in the past tense?',
   o:['She plays cricket.','She will play cricket.','She played cricket.','She is playing cricket.'],
   a:2,t:'Verbs',e:'"Played" is the past tense — it already happened.'},
  {id:'g09',q:'Choose the correct verb:\n"The dogs ___ in the garden."',
   o:['is playing','am playing','are playing','was playing'],a:2,t:'Verbs',
   e:'"Dogs" is plural, so we use "are playing."'},
  {id:'g10',q:'Which word is a verb?',
   o:['happy','quickly','jump','blue'],a:2,t:'Verbs',e:'"Jump" is a verb — it is an action word.'},

  /* ── Adjectives ── */
  {id:'g11',q:'Which word is an adjective (describing word) in: "The tiny frog sat on the log."?',
   o:['sat','frog','tiny','log'],a:2,t:'Adjectives',e:'"Tiny" describes the noun "frog" — it is an adjective.'},
  {id:'g12',q:'Choose the adjective that best completes: "The ___ koala slept in the tree."',
   o:['quickly','sleepy','jumped','very'],a:1,t:'Adjectives',e:'"Sleepy" describes the koala — it is an adjective.'},
  {id:'g13',q:'Which sentence uses an adjective?',
   o:['The bird sang.','The bird flew quickly.','The colourful bird sang.','The bird sang loudly.'],
   a:2,t:'Adjectives',e:'"Colourful" is an adjective — it describes what the bird looks like.'},
  {id:'g14',q:'Choose the comparative adjective:\n"This book is ___ than that one."',
   o:['long','longest','longer','most long'],a:2,t:'Adjectives',
   e:'When comparing two things we use -er: "longer."'},
  {id:'g15',q:'Which is the superlative form of "big"?',
   o:['bigger','most big','biggest','more big'],a:2,t:'Adjectives',
   e:'"Biggest" is the superlative — used when comparing three or more things.'},

  /* ── Adverbs ── */
  {id:'g16',q:'Which word is an adverb in: "She ran quickly to catch the bus."?',
   o:['ran','she','bus','quickly'],a:3,t:'Adverbs',e:'"Quickly" is an adverb — it describes how she ran.'},
  {id:'g17',q:'Which word tells us WHEN something happened?',
   o:['carefully','loudly','yesterday','happily'],a:2,t:'Adverbs',e:'"Yesterday" is a time adverb — it tells us when.'},
  {id:'g18',q:'Choose the adverb that completes: "The baby ___ fell asleep."',
   o:['peaceful','peace','peacefully','peaced'],a:2,t:'Adverbs',
   e:'"Peacefully" is an adverb (peaceful + ly) — it describes how the baby fell asleep.'},

  /* ── Pronouns ── */
  {id:'g19',q:'Replace the underlined noun with a pronoun:\n"Jake and Emma went to the park."',
   o:['It went to the park.','He went to the park.','They went to the park.','She went to the park.'],
   a:2,t:'Pronouns',e:'"They" replaces two people (Jake and Emma).'},
  {id:'g20',q:'Which pronoun replaces "the dog" in: "The dog is barking."?',
   o:['She','He','They','It'],a:3,t:'Pronouns',e:'We use "it" for animals and things when we don\'t know the gender.'},
  {id:'g21',q:'Choose the correct pronoun:\n"___ and I went to the park." (Mevil)',
   o:['Him','Me','Mevil','He'],a:3,t:'Pronouns',
   e:'"He and I went to the park." — use subject pronoun "he" before "and I."'},

  /* ── Conjunctions ── */
  {id:'g22',q:'Choose the conjunction that joins these sentences:\n"I wanted to play outside. It was raining."',
   o:['and','but','so','or'],a:1,t:'Conjunctions',
   e:'"But" shows contrast — wanting to play but it was raining.'},
  {id:'g23',q:'Which conjunction fits?\n"She studied hard ___ she could pass the test."',
   o:['but','or','so that','and'],a:2,t:'Conjunctions',
   e:'"So that" shows purpose — she studied so that she could pass.'},
  {id:'g24',q:'Choose the best conjunction:\n"You can have a biscuit ___ a piece of fruit."',
   o:['but','because','or','so'],a:2,t:'Conjunctions',
   e:'"Or" gives a choice between two options.'},
  {id:'g25',q:'Which sentence uses "because" correctly?',
   o:['She was late because the bus.','She was late because missed the bus.','She was late because she missed the bus.','Because she was late the bus.'],
   a:2,t:'Conjunctions',e:'"Because" explains a reason — she was late because she missed the bus.'},

  /* ── Prepositions ── */
  {id:'g26',q:'Choose the preposition in: "The cat sat under the table."',
   o:['cat','sat','under','table'],a:2,t:'Prepositions',e:'"Under" is a preposition — it tells us where the cat sat.'},
  {id:'g27',q:'Which preposition correctly completes: "The ball is ___ the box."',
   o:['inside','running','quickly','is'],a:0,t:'Prepositions',
   e:'"Inside" is a preposition showing where the ball is.'},

  /* ── Capital Letters ── */
  {id:'g28',q:'Which word in this sentence needs a capital letter?\n"my friend lives in sydney."',
   o:['friend','lives','sydney','in'],a:2,t:'Capital Letters',
   e:'"Sydney" is a proper noun (a place name) and must start with a capital letter.'},
  {id:'g29',q:'Which sentence uses capital letters correctly?',
   o:['we went to Melbourne zoo.','We went to Melbourne Zoo.','We went to melbourne zoo.','we went to Melbourne Zoo.'],
   a:1,t:'Capital Letters',e:'The sentence starts with "We" (capital). Melbourne Zoo is a proper noun — both words capitalised.'},
  {id:'g30',q:'Which words should have capital letters?\n"on tuesday, zara met her friend bella at flinders street station."',
   o:['Tuesday, Zara, Bella, Flinders Street Station','tuesday, zara, bella, flinders','On, Tuesday, met, friend','tuesday, zara, bella, flinders street station'],
   a:0,t:'Capital Letters',e:'Proper nouns (names of people, days, and places) need capital letters.'},
  {id:'g31',q:'Which sentence is punctuated correctly?',
   o:['i love going to school','I love going to school.','I love going to School.','i Love going to school.'],
   a:1,t:'Capital Letters',e:'Sentences start with a capital letter and end with a full stop.'},

  /* ── Full Stops, Question Marks & Exclamation Marks ── */
  {id:'g32',q:'Which punctuation mark ends this sentence?\n"What time does the train leave"',
   o:['.','!','?',','],a:2,t:'Punctuation',e:'Questions end with a question mark (?).'},
  {id:'g33',q:'Which sentence uses punctuation correctly?',
   o:['The dog barked?','Look out!','Where are you.','How old are you!'],
   a:1,t:'Punctuation',e:'"Look out!" is an exclamation — it uses an exclamation mark correctly.'},
  {id:'g34',q:'Add the correct punctuation:\n"She loves cats dogs and rabbits"',
   o:['She loves cats, dogs, and rabbits.','She loves cats dogs and rabbits?','She loves, cats dogs, and rabbits.','She loves cats dogs and rabbits!'],
   a:0,t:'Punctuation',e:'Commas separate items in a list. The sentence ends with a full stop.'},
  {id:'g35',q:'Which sentence needs an exclamation mark?',
   o:['The cat is on the mat','Where is my lunch','Watch out for the snake','She went to school'],
   a:2,t:'Punctuation',e:'"Watch out for the snake!" — this shows urgency and strong feeling, so it needs an exclamation mark.'},

  /* ── Commas ── */
  {id:'g36',q:'Where does the comma go?\n"At the market we bought apples oranges and bananas."',
   o:['After "market" and between each item','Only after "oranges"','After "bought"','No comma needed'],
   a:0,t:'Punctuation',e:'A comma follows the introductory phrase ("At the market,") and separates list items: apples, oranges, and bananas.'},
  {id:'g37',q:'Which sentence uses commas correctly?',
   o:['We visited Mum, Dad, and, Grandma.','We visited, Mum Dad and Grandma.','We visited Mum, Dad, and Grandma.','We, visited Mum Dad and Grandma.'],
   a:2,t:'Punctuation',e:'Commas go between items in a list: Mum, Dad, and Grandma.'},

  /* ── Apostrophes ── */
  {id:'g38',q:'Which sentence uses an apostrophe correctly?',
   o:['The dog\'s bone is buried.','The dogs bone is buried.','The dog\'s bone\'s are buried.','The dogs\' bone is buried.'],
   a:0,t:'Apostrophes',e:'"Dog\'s" — apostrophe + s shows the bone belongs to the dog.'},
  {id:'g39',q:'What does the apostrophe do in "don\'t"?',
   o:['It shows belonging.','It replaces a missing letter.','It ends the sentence.','It shows a list.'],
   a:1,t:'Apostrophes',e:'"Don\'t" = do not. The apostrophe replaces the missing letter "o".'},
  {id:'g40',q:'Choose the correct contraction for "I am".',
   o:['Im','I\'am','I\'m','Ia\'m'],a:2,t:'Apostrophes',e:'"I\'m" = I am. The apostrophe replaces the "a" in "am."'},
  {id:'g41',q:'Which word is a contraction?',
   o:['cannot','she\'s','quickly','running'],a:1,t:'Apostrophes',e:'"She\'s" is a contraction of "she is" or "she has."'},

  /* ── Speech Marks ── */
  {id:'g42',q:'Choose the sentence that uses speech marks correctly.',
   o:['"Come here", she said.','Come here, "she said."','"Come here" she said.','Come here," she said.'],
   a:0,t:'Punctuation',e:'Speech marks surround the spoken words. Punctuation goes inside the closing speech mark.'},
  {id:'g43',q:'Which sentence shows what someone said?',
   o:['Mia thought about lunch.','Mia said, "Let\'s go to the park!"','Mia walked to school.','Mia ate her lunch quietly.'],
   a:1,t:'Punctuation',e:'The sentence with "said" and speech marks shows direct speech — what Mia actually said.'},

  /* ── Sentence Types ── */
  {id:'g44',q:'Which sentence is a command?',
   o:['Is it raining?','What a lovely day!','Please sit down.','The bird is singing.'],
   a:2,t:'Sentences',e:'"Please sit down" is a command — it tells someone to do something.'},
  {id:'g45',q:'Which is an exclamation?',
   o:['The dog ran home.','Where is the dog?','What an amazing jump!','Bring me the dog.'],
   a:2,t:'Sentences',e:'"What an amazing jump!" is an exclamation — it shows strong feeling.'},
  {id:'g46',q:'Which sentence is a question?',
   o:['Stop that now.','The rain fell heavily.','Have you seen my cat?','What a great idea!'],
   a:2,t:'Sentences',e:'"Have you seen my cat?" is a question — it asks for information and ends with a question mark.'},
  {id:'g47',q:'Which is a complete sentence?',
   o:['Running fast.','The big dog.','She runs fast.','Very quickly outside.'],
   a:2,t:'Sentences',e:'"She runs fast" has a subject (she) and a verb (runs) — it is a complete sentence.'},

  /* ── Subject–Verb Agreement ── */
  {id:'g48',q:'Choose the correct sentence.',
   o:['The birds flies south.','The bird fly south.','The birds fly south.','The birds flys south.'],
   a:2,t:'Subject-Verb Agreement',e:'"Birds" is plural, so the verb is "fly" (no s).'},
  {id:'g49',q:'Which sentence is correct?',
   o:['He don\'t like broccoli.','He doesn\'t likes broccoli.','He doesn\'t like broccoli.','He do not likes broccoli.'],
   a:2,t:'Subject-Verb Agreement',e:'"He doesn\'t like" — use doesn\'t (does not) for third person singular (he/she/it).'},
  {id:'g50',q:'Choose the correct form:\n"There ___ two kookaburras in the tree."',
   o:['is','am','was','are'],a:3,t:'Subject-Verb Agreement',
   e:'"Two kookaburras" is plural, so we use "are."'},

  /* ── Sentence Combining & Structure ── */
  {id:'g51',q:'Combine these sentences using a conjunction:\n"Mevil likes cricket. He also likes swimming."',
   o:['Mevil likes cricket, and he also likes swimming.','Mevil likes cricket but he also likes swimming so.','Mevil likes cricket. He also likes swimming, and.','Mevil, cricket, swimming.'],
   a:0,t:'Sentences',e:'"And" joins the two ideas smoothly into one sentence.'},
  {id:'g52',q:'Which sentence is written in the correct order?',
   o:['Quickly the ran cheetah.','The cheetah quickly ran.','Ran the quickly cheetah.','Quickly ran the cheetah'],
   a:1,t:'Sentences',e:'"The cheetah quickly ran" — subject, then verb modified by adverb — correct English word order.'},
  {id:'g53',q:'Which is the best way to combine: "It was hot. We went swimming."',
   o:['It was hot so we went swimming.','It was hot, we went swimming.','Hot it was we went swimming.','It was hot but we went swimming.'],
   a:0,t:'Sentences',e:'"So" shows cause and effect — it was hot, so (as a result) we went swimming.'},

  /* ── Tense Consistency ── */
  {id:'g54',q:'Which sentence is written correctly in past tense?',
   o:['Yesterday she walks to school.','Yesterday she walked to school.','Yesterday she is walking to school.','Yesterday she will walk to school.'],
   a:1,t:'Tense',e:'"Walked" is the past tense. Yesterday signals the action already happened.'},
  {id:'g55',q:'Choose the correct future tense sentence.',
   o:['She went to the zoo tomorrow.','She goes to the zoo tomorrow.','She will go to the zoo tomorrow.','She gone to the zoo tomorrow.'],
   a:2,t:'Tense',e:'"Will go" is future tense — it hasn\'t happened yet.'},
  {id:'g56',q:'Which sentence is in present tense?',
   o:['She played football.','She is playing football.','She will play football.','She had played football.'],
   a:1,t:'Tense',e:'"Is playing" — present continuous tense, happening right now.'},

  /* ── Mixed Grammar ── */
  {id:'g57',q:'Which word is missing from this sentence?\n"She going to the park."',
   o:['not','is','very','and'],a:1,t:'Verbs',
   e:'"She is going to the park" — the auxiliary verb "is" is missing.'},
  {id:'g58',q:'Choose the correct article:\n"I saw ___ elephant at the zoo."',
   o:['a','an','the','some'],a:1,t:'Articles',
   e:'"An" is used before words that start with a vowel sound. "An elephant."'},
  {id:'g59',q:'Which sentence has correct grammar?',
   o:['I seen a movie.','I have saw a movie.','I watched a movie.','I have watch a movie.'],
   a:2,t:'Verbs',e:'"I watched a movie" — simple past tense, correct form.'},
  {id:'g60',q:'Choose the word that completes the sentence correctly:\n"She is ___ than her brother."',
   o:['tall','taller','tallest','most tall'],a:1,t:'Adjectives',
   e:'"Taller" — comparative adjective used when comparing two people.'},
  {id:'g61',q:'Which sentence uses "its" correctly?',
   o:['The dog wagged it\'s tail.','The dog wagged its tail.','The dog wagged its\' tail.','The dog wagged it tail.'],
   a:1,t:'Apostrophes',e:'"Its" (no apostrophe) shows belonging — the tail belonging to the dog. "It\'s" = it is.'},
  {id:'g62',q:'Choose the correctly punctuated sentence.',
   o:['"Can I help you" she asked?','"Can I help you?" she asked.','"Can I help you," she asked?','"Can I help you?" she asked!'],
   a:1,t:'Punctuation',e:'The question mark goes inside the speech marks, and the attribution "she asked" ends with a full stop.'}
];
