// ═══════════════════════════════════════════════════════
//  PART 2 — ICAS Science & ICAS Digital Technology
//  Victorian Curriculum Year 2 (VCAA) — Casey Fields PS
//  Science = 25Q/50min | Digital Tech = 30Q/50min
// ═══════════════════════════════════════════════════════
window.QB = window.QB || {};

// ─────────────────────────────────────────────────────
//  ICAS SCIENCE  (75 questions)
//  VCSSU040 Materials · VCSSU041 Earth & Space
//  VCSSU042 Biological · VCSSU043 Physical
//  VCSIS Inquiry Skills
// ─────────────────────────────────────────────────────
window.QB.icas_science = [

// ══ BIOLOGICAL SCIENCES — Living Things (VCSSU042) ══

// Living vs Non-living
{id:'s01',q:'Which of these is a LIVING thing?',o:['A rock','A river','A wattle tree','A cloud'],a:2,t:'Living Things',e:'A wattle tree is living — it grows, needs nutrients and water, reproduces and responds to its environment.'},
{id:'s02',q:'Which characteristic do ALL living things share?',o:['They can fly','They live in water','They grow and reproduce','They are green'],a:2,t:'Living Things',e:'All living things grow and can reproduce (make more of themselves). This applies to plants, animals and fungi.'},
{id:'s03',q:'A plastic bottle is non-living because it:',o:['Is too heavy','Cannot move by itself, grow or reproduce','Is made in a factory','Is not found in nature'],a:1,t:'Living Things',e:'Non-living things do not grow, reproduce or respond to their environment the way living things do.'},
{id:'s04',q:'Which list contains ONLY living things?',o:['Dog, rock, tree','Koala, grass, mushroom','River, cloud, fern','Mountain, worm, sand'],a:1,t:'Living Things',e:'Koala, grass and mushroom are all living — they grow, feed and reproduce.'},
{id:'s05',q:'What do living things need to survive? Choose the BEST answer.',o:['Sunlight only','Food, water and air','Plastic and metal','A home and toys'],a:1,t:'Living Things',e:'All living things need food/nutrients, water and air (or dissolved oxygen) to survive.'},

// Australian Animals & Habitats
{id:'s06',q:'A koala eats mainly eucalyptus (gum tree) leaves. What type of feeder is it?',o:['Carnivore','Herbivore','Omnivore','Decomposer'],a:1,t:'Animals',e:'A herbivore eats only plants. Koalas eat eucalyptus leaves — plant material only.'},
{id:'s07',q:'Which Australian animal is a MARSUPIAL (carries young in a pouch)?',o:['Platypus','Echidna','Wombat','Blue-tongue lizard'],a:2,t:'Animals',e:'Wombats are marsupials — females have a pouch where joeys develop after birth. (Platypus and echidna are monotremes.)'},
{id:'s08',q:'The platypus uses its bill to detect electric signals from prey underwater. This is an example of:',o:['Camouflage','Adaptation','Reproduction','Migration'],a:1,t:'Animals',e:'An adaptation is a feature that helps an animal survive in its environment. The platypus\'s bill is an adaptation for finding food.'},
{id:'s09',q:'Where would you MOST LIKELY find a platypus in Victoria?',o:['In a dry desert','In a freshwater stream or river','In the ocean','In a tall mountain',''],a:1,t:'Animals',e:'Platypuses live in freshwater rivers and streams — they are found in eastern Australian waterways including in Victoria.'},
{id:'s10',q:'Which animal uses camouflage to hide from predators?',o:['Kookaburra','Leaf-tailed gecko','Wedge-tailed eagle','Blue whale'],a:1,t:'Animals',e:'The leaf-tailed gecko has a body shaped and coloured exactly like bark and leaves, making it nearly invisible.'},
{id:'s11',q:'A kookaburra eats lizards, snakes and insects. What type of feeder is it?',o:['Herbivore','Carnivore','Omnivore','Producer'],a:1,t:'Animals',e:'A carnivore eats other animals. The kookaburra eats only animals (lizards, snakes, large insects).'},
{id:'s12',q:'Which feature helps a duck swim on water?',o:['Sharp claws','Webbed feet','Hollow bones','Feathers on its head'],a:1,t:'Animals',e:'Webbed feet act like paddles, helping ducks push through water efficiently — an adaptation for swimming.'},
{id:'s13',q:'Bats sleep during the day and are active at night. Animals that do this are called:',o:['Migratory','Nocturnal','Camouflaged','Hibernating'],a:1,t:'Animals',e:'Nocturnal animals are active at night and rest during the day. Many Australian animals are nocturnal.'},
{id:'s14',q:'Which Australian animal lays eggs AND feeds its young with milk?',o:['Kangaroo','Koala','Echidna','Tiger snake'],a:2,t:'Animals',e:'The echidna (and platypus) are monotremes — they lay eggs but also produce milk to feed their young.'},
{id:'s15',q:'A tiger snake is found near wetlands and waterways in Victoria. Its habitat is:',o:['Desert','Rainforest','Wetlands and grasslands','Ocean reefs'],a:2,t:'Animals',e:'Tiger snakes in Victoria live near water sources — wetlands, creek banks and coastal heathlands.'},

// Life Cycles
{id:'s16',q:'What is the correct order of a butterfly\'s life cycle?',o:['Egg → Butterfly → Caterpillar → Chrysalis','Caterpillar → Egg → Butterfly → Chrysalis','Egg → Caterpillar → Chrysalis → Butterfly','Chrysalis → Egg → Caterpillar → Butterfly'],a:2,t:'Life Cycles',e:'Egg → Caterpillar (larva) → Chrysalis (pupa) → Butterfly (adult). This is called complete metamorphosis.'},
{id:'s17',q:'A frog begins life as a tadpole. As it grows it develops:',o:['Wings and feathers','Legs and loses its tail','A shell on its back','Fur and claws'],a:1,t:'Life Cycles',e:'Tadpoles grow legs, their tail shrinks and is absorbed, and they become adult frogs — this is metamorphosis.'},
{id:'s18',q:'Which stage comes AFTER the egg in a chicken\'s life cycle?',o:['Adult hen','Chick','Rooster','Embryo in shell'],a:1,t:'Life Cycles',e:'Egg → Chick (hatches from egg) → Juvenile → Adult chicken. The chick hatches from the egg.'},
{id:'s19',q:'Plants and animals produce OFFSPRING so that:',o:['They can play together','Their species continues to survive','They have company','They grow faster'],a:1,t:'Life Cycles',e:'Reproduction produces offspring (young) so that the species does not die out — it continues to survive.'},
{id:'s20',q:'A joey (baby kangaroo) is born very small and underdeveloped. It climbs into its mother\'s pouch to:',o:['Keep warm in winter only','Sleep through summer','Continue developing and feed on milk','Hide from predators'],a:2,t:'Life Cycles',e:'Joeys are born after only 33 days and are very tiny. They spend months in the pouch developing further and drinking their mother\'s milk.'},

// Plants
{id:'s21',q:'Which part of a plant absorbs water and nutrients from the soil?',o:['Leaves','Stem','Roots','Flowers'],a:2,t:'Plants',e:'Roots anchor the plant in the soil and absorb water and dissolved minerals.'},
{id:'s22',q:'What do plants need to make their own food (photosynthesis)?',o:['Moonlight, soil and sugar','Sunlight, water and carbon dioxide','Sunlight, sugar and oxygen','Water, warmth and insects'],a:1,t:'Plants',e:'Photosynthesis uses sunlight + water + CO₂ → glucose (food) + oxygen.'},
{id:'s23',q:'When a wattle seed sprouts and begins to grow, this process is called:',o:['Photosynthesis','Pollination','Germination','Evaporation'],a:2,t:'Plants',e:'Germination is when a seed absorbs water, swells and begins to sprout its first root and shoot.'},
{id:'s24',q:'Bees visit banksia flowers to collect nectar. As they move between flowers they transfer pollen. This is called:',o:['Germination','Pollination','Evaporation','Adaptation'],a:1,t:'Plants',e:'Pollination occurs when pollen is transferred from one flower to another, enabling fertilisation and seed production.'},
{id:'s25',q:'What gas do plants release into the air during photosynthesis?',o:['Carbon dioxide','Nitrogen','Oxygen','Hydrogen'],a:2,t:'Plants',e:'Plants take in CO₂ and release oxygen as a by-product of photosynthesis — which is why plants are important for the air we breathe.'},
{id:'s26',q:'A mountain ash tree in the Dandenong Ranges can grow over 80 metres tall. Which part carries water from the roots to the leaves?',o:['Flowers','Stem/trunk','Seeds','Bark only'],a:1,t:'Plants',e:'The stem (or trunk in trees) contains tubes called xylem that transport water from roots up to the leaves.'},
{id:'s27',q:'Why do some flowers have bright colours and sweet smells?',o:['To protect themselves from rain','To attract insects and birds for pollination','To grow faster in sunlight','To stop animals from eating them'],a:1,t:'Plants',e:'Bright colours and sweet scents attract pollinators (bees, butterflies, birds) which help the flower reproduce.'},

// ══ CHEMICAL SCIENCES — Properties of Materials (VCSSU040) ══

{id:'s28',q:'Which property makes glass a good material for a window?',o:['It is magnetic','It is transparent (see-through)','It is flexible','It floats on water'],a:1,t:'Materials',e:'Glass is transparent — light passes through it clearly, allowing people to see outside while being protected from weather.'},
{id:'s29',q:'Which material would be BEST for making a raincoat?',o:['Paper','Cotton fabric','Waterproof nylon','Cardboard'],a:2,t:'Materials',e:'A raincoat needs to be waterproof. Nylon and other synthetic fabrics repel water effectively.'},
{id:'s30',q:'A rubber band can be stretched and returns to its original shape. This property is called:',o:['Hardness','Elasticity','Transparency','Magnetism'],a:1,t:'Materials',e:'Elasticity is the ability to stretch and return to the original shape when the force is removed.'},
{id:'s31',q:'Which object would a magnet be able to pick up?',o:['Wooden ruler','Glass marble','Steel paperclip','Plastic eraser'],a:2,t:'Materials',e:'Magnets attract ferromagnetic metals — iron and steel. A steel paperclip is attracted to a magnet.'},
{id:'s32',q:'Ice is water in its ___ state.',o:['Liquid','Gas','Solid','Plasma'],a:2,t:'Materials',e:'Ice is frozen water — water in its solid state. It has a definite shape and volume.'},
{id:'s33',q:'When water is heated strongly it turns into steam. This change is called:',o:['Freezing','Condensation','Evaporation','Melting'],a:2,t:'Materials',e:'Evaporation (or boiling) is when liquid water gains enough energy to become water vapour (steam/gas).'},
{id:'s34',q:'Which material is OPAQUE (you cannot see through it)?',o:['Clear glass','Thin plastic wrap','Brick wall','Frosted glass'],a:2,t:'Materials',e:'Opaque materials do not let any light through. A brick wall blocks all light.'},
{id:'s35',q:'Why is metal used to make cooking pots?',o:['Metal is light and cheap','Metal is a good conductor of heat','Metal is transparent','Metal does not get hot'],a:1,t:'Materials',e:'Metal conducts (transfers) heat well — heat from the stove passes through the metal pot to cook the food inside.'},
{id:'s36',q:'A scientist tests whether different materials sink or float. This is testing the property of:',o:['Magnetism','Transparency','Buoyancy','Hardness'],a:2,t:'Materials',e:'Buoyancy is the ability to float. Objects less dense than water float; denser objects sink.'},
{id:'s37',q:'Which change CANNOT be reversed (cannot be undone)?',o:['Ice melting into water','Salt dissolving in water','Paper being burnt to ash','Water evaporating into steam'],a:2,t:'Materials',e:'Burning paper creates ash — a completely new material. This cannot be reversed. The other changes can be undone (freeze water, evaporate water to get salt back, condense steam).'},
{id:'s38',q:'A builder needs a material that is hard, strong and does not rot in the rain. Which is BEST?',o:['Cardboard','Cotton fabric','Brick','Paper'],a:2,t:'Materials',e:'Brick is hard, strong and very resistant to water and weathering — ideal for building.'},
{id:'s39',q:'Which solid material can be bent into different shapes without breaking?',o:['Glass','Ceramic','Wire (metal)','Dry chalk'],a:2,t:'Materials',e:'Thin metal wire is malleable (can be bent) — a property that makes metal very useful for making different shapes.'},
{id:'s40',q:'Sugar stirred into water seems to disappear. What has happened?',o:['The sugar was destroyed','The sugar dissolved into the water','The sugar evaporated','The sugar melted like ice'],a:1,t:'Materials',e:'Sugar dissolves — it breaks into tiny particles that spread through the water. The sugar is still there (you can taste it).'},

// ══ EARTH & SPACE SCIENCES (VCSSU041) ══

{id:'s41',q:'What causes DAY and NIGHT on Earth?',o:['The Moon moves around Earth','Earth moves closer to and away from the Sun','Earth spins (rotates) on its axis every 24 hours','The Sun moves around Earth'],a:2,t:'Earth & Space',e:'Earth rotates on its axis once every 24 hours. The side facing the Sun has day; the side facing away has night.'},
{id:'s42',q:'Which season comes after AUTUMN in Victoria?',o:['Summer','Spring','Winter','Another Autumn'],a:2,t:'Earth & Space',e:'Victorian seasons: Summer (Dec-Feb) → Autumn (Mar-May) → Winter (Jun-Aug) → Spring (Sep-Nov).'},
{id:'s43',q:'What is the main SOURCE of energy for Earth?',o:['The Moon','The wind','The Sun','Volcanoes'],a:2,t:'Earth & Space',e:'The Sun provides light and heat energy that drives weather, plant growth, water cycle and almost all life on Earth.'},
{id:'s44',q:'Rain, snow, rivers and oceans are all forms of:',o:['Air','Rock','Water','Soil'],a:2,t:'Earth & Space',e:'Water exists in many forms and places on Earth — liquid (rain, rivers, oceans), solid (snow, ice) and gas (water vapour in clouds).'},
{id:'s45',q:'Water from a puddle disappears on a warm sunny day. Where does it go?',o:['Into the ground forever','It is destroyed by sunlight','It evaporates and becomes water vapour in the air','It flows into drains'],a:2,t:'Earth & Space',e:'The Sun\'s heat evaporates the water — it becomes invisible water vapour that rises into the atmosphere.'},
{id:'s46',q:'Which type of cloud is tall, dark and brings heavy thunderstorms?',o:['Cirrus (wispy, high up)','Cumulus (white and fluffy)','Cumulonimbus (tall, dark storm cloud)','Stratus (flat, grey sheet)'],a:2,t:'Earth & Space',e:'Cumulonimbus clouds are towering storm clouds that bring heavy rain, thunder, lightning and sometimes hail.'},
{id:'s47',q:'In Melbourne, in which months is it WINTER?',o:['December, January, February','March, April, May','June, July, August','September, October, November'],a:2,t:'Earth & Space',e:'Australian seasons are opposite to the Northern Hemisphere. Victorian winter = June, July, August.'},
{id:'s48',q:'Why do we have SEASONS?',o:['Earth moves closer to the Sun in summer','Earth is tilted on its axis as it orbits the Sun','The Sun gets hotter and cooler','The Moon blocks the Sun\'s heat in winter'],a:1,t:'Earth & Space',e:'Earth\'s tilt (23.5°) means different parts receive more or less direct sunlight throughout the year, creating seasons.'},
{id:'s49',q:'Water that falls from clouds as rain is part of which cycle?',o:['Rock cycle','Carbon cycle','Water cycle','Food cycle'],a:2,t:'Earth & Space',e:'The water cycle: evaporation → condensation (clouds form) → precipitation (rain/snow) → collection → evaporation again.'},
{id:'s50',q:'Port Phillip Bay is a large body of SALT water near Melbourne. It is called a:',o:['Lake','River','Bay (part of the ocean)','Reservoir'],a:2,t:'Earth & Space',e:'Port Phillip Bay is a large sheltered coastal bay — a body of salt water connected to the Southern Ocean.'},
{id:'s51',q:'A thermometer measures:',o:['Rainfall','Wind speed','Temperature','Air pressure'],a:2,t:'Earth & Space',e:'A thermometer measures temperature in degrees Celsius (°C) in Australia.'},
{id:'s52',q:'What happens to most plants in Victoria during WINTER?',o:['They grow very fast','They grow flowers','They slow down or stop growing due to less sunlight and cold','They die completely'],a:2,t:'Earth & Space',e:'Less sunlight and colder temperatures in winter slow plant growth. Deciduous trees lose their leaves; others just grow more slowly.'},

// ══ PHYSICAL SCIENCES — Forces, Light & Sound (VCSSU043) ══

{id:'s53',q:'What is a FORCE?',o:['A type of energy stored in batteries','A push or a pull that can change how objects move','A type of material','The speed of an object'],a:1,t:'Forces',e:'A force is a push or pull. Forces can make objects start moving, stop, speed up, slow down or change direction.'},
{id:'s54',q:'When you kick an AFL football, which type of force are you applying?',o:['A pull','A magnetic force','A push','Gravity'],a:2,t:'Forces',e:'Kicking is a push — your foot pushes the ball forward.'},
{id:'s55',q:'What force pulls everything towards the centre of the Earth?',o:['Friction','Magnetism','Electricity','Gravity'],a:3,t:'Forces',e:'Gravity is the invisible force of attraction between objects with mass. Earth\'s gravity pulls everything downward.'},
{id:'s56',q:'A book slides across a table and slows down. The force that slows it is:',o:['Gravity','Magnetism','Friction','Electricity'],a:2,t:'Forces',e:'Friction acts between the surfaces of the book and the table, opposing movement and slowing the book down.'},
{id:'s57',q:'Which surface would create the MOST friction for a sliding toy car?',o:['Smooth glass','Wet ice','Rough carpet','Polished marble'],a:2,t:'Forces',e:'Rough surfaces create more friction than smooth ones. Carpet is roughest of these options.'},
{id:'s58',q:'Squeezing a lump of playdough changes its SHAPE. Which force does this?',o:['Gravity pulling it down','A push from your hands','Magnetic force','Friction between surfaces'],a:1,t:'Forces',e:'Squeezing applies a push (compression force) from your hands, which deforms and changes the shape of the playdough.'},
{id:'s59',q:'A ball thrown upward always comes back down. Why?',o:['The wind pushes it','Friction slows it','Gravity pulls it back toward Earth','The air is too heavy'],a:2,t:'Forces',e:'Gravity continuously pulls the ball back toward Earth\'s surface, regardless of how high it goes.'},
{id:'s60',q:'Which example shows a PULL force?',o:['Pushing a pram up a hill','Kicking a soccer ball','Opening a drawer by pulling the handle','Hitting a cricket ball with a bat'],a:2,t:'Forces',e:'Pulling a drawer handle is a pull force — you are pulling the drawer toward you.'},

// Sound
{id:'s61',q:'How is SOUND made?',o:['By objects changing colour','By objects vibrating (shaking quickly)','By objects getting heavier','By objects cooling down'],a:1,t:'Sound & Light',e:'All sounds are created by vibrations. When an object vibrates it causes the surrounding air to vibrate, which travels to our ears as sound.'},
{id:'s62',q:'You can hear a kookaburra calling from far away. This is because sound:',o:['Travels only in water','Travels through the air','Only travels upward','Cannot travel far'],a:1,t:'Sound & Light',e:'Sound travels as waves through the air. It can travel long distances, which is why we can hear distant sounds.'},
{id:'s63',q:'Which material would ABSORB sound best in a music room?',o:['Hard concrete walls','Glass windows','Thick foam padding on walls','Metal sheets'],a:2,t:'Sound & Light',e:'Soft, thick materials like foam absorb sound energy rather than bouncing it back (reflecting it).'},
{id:'s64',q:'A guitar makes a louder sound when you pluck the strings harder. This means:',o:['The pitch changes','The volume (loudness) changes','The material changes','The string stops vibrating'],a:1,t:'Sound & Light',e:'Plucking harder creates larger vibrations, which produce a louder sound. Pitch (high/low) is different from volume (loud/quiet).'},

// Light
{id:'s65',q:'We can see a kookaburra sitting on a branch because:',o:['The kookaburra produces its own light','Light bounces off the kookaburra into our eyes','Our eyes send light out to see things','The kookaburra is very colourful'],a:1,t:'Sound & Light',e:'We see objects because light (from the Sun or a lamp) reflects (bounces) off them into our eyes.'},
{id:'s66',q:'A shadow forms when an object:',o:['Reflects all light','Absorbs colour','Blocks light from passing through','Creates its own light'],a:2,t:'Sound & Light',e:'Opaque objects block light. The area behind them where no light reaches is called a shadow.'},
{id:'s67',q:'In which direction does a shadow move as the Sun moves across the sky during the day?',o:['It stays in the same place','It grows shorter at noon and longer in the morning and afternoon','It only appears at night','It moves randomly'],a:1,t:'Sound & Light',e:'Shadows are longest in the morning and afternoon (when the Sun is low) and shortest at noon (when the Sun is highest). They swing from west to east during the day.'},
{id:'s68',q:'Which object produces its OWN light (a light source)?',o:['The Moon','A mirror','A cat\'s eyes in the dark','A torch (flashlight)'],a:3,t:'Sound & Light',e:'A torch produces its own light. The Moon, mirrors and cats\' eyes only reflect light from other sources.'},

// ══ SCIENCE INQUIRY SKILLS (VCSIS) ══

{id:'s69',q:'Before doing an experiment, a scientist makes a prediction called a:',o:['Result','Hypothesis','Method','Conclusion'],a:1,t:'Science Inquiry',e:'A hypothesis is an educated prediction about what you think will happen, based on what you already know.'},
{id:'s70',q:'Why do scientists repeat their experiments several times?',o:['To make it take longer','To check the results are reliable and not just a coincidence','To use more equipment','To get different results each time'],a:1,t:'Science Inquiry',e:'Repeating experiments checks that results are consistent and reliable, not just a chance occurrence.'},
{id:'s71',q:'A class is testing which paper towel absorbs the most water. To make it a FAIR TEST, they should:',o:['Use different sizes of paper towel','Use different amounts of water each time','Use the same amount of water for each paper towel','Use towels from different stores'],a:2,t:'Science Inquiry',e:'A fair test changes only ONE variable (the type of towel) and keeps everything else the same (same amount of water, same conditions).'},
{id:'s72',q:'After doing an experiment, what should a scientist write down?',o:['Only what they expected to happen','Only the results that prove their hypothesis','All observations honestly, even surprising results','Only positive results'],a:2,t:'Science Inquiry',e:'Scientists must record ALL results honestly. Unexpected results are just as valuable as expected ones.'},
{id:'s73',q:'Mevil notices that plants near the window grow taller than plants in a dark corner. A good question to investigate would be:',o:['Do plants like music?','Does the amount of light affect how tall a plant grows?','Are plants alive?','Do plants drink water?'],a:1,t:'Science Inquiry',e:'A good scientific question is testable and specific. This question can be investigated by varying the amount of light.'},
{id:'s74',q:'Which tool would a scientist use to measure how much rain fell during a storm?',o:['Thermometer','Rain gauge','Magnifying glass','Balance scales'],a:1,t:'Science Inquiry',e:'A rain gauge is a container that collects and measures rainfall in millimetres (mm).'},
{id:'s75',q:'A magnifying glass is used to:',o:['Measure temperature','Make objects appear larger for closer observation','Test if materials conduct electricity','Measure mass'],a:1,t:'Science Inquiry',e:'A magnifying glass (hand lens) makes objects appear larger so we can observe small details more easily.'},
];

// ─────────────────────────────────────────────────────
//  ICAS DIGITAL TECHNOLOGY  (70 questions)
//  Victorian Curriculum Year 3 level (ahead of Year 2)
//  VCDTDS013 · VCDTDI015 · VCDTCD017 · VCDTCD019
// ─────────────────────────────────────────────────────
window.QB.icas_digital = [

// ══ DIGITAL SYSTEMS — Hardware & Software (VCDTDS013) ══

{id:'d01',q:'Which of these is a DIGITAL DEVICE?',o:['A wooden ruler','A pencil','A tablet computer','A whiteboard'],a:2,t:'Digital Devices',e:'A tablet is a digital device — it processes and stores digital information using electronic circuits.'},
{id:'d02',q:'What is the difference between HARDWARE and SOFTWARE?',o:['Hardware is the programs; software is the physical parts','Hardware is the physical parts you can touch; software is the programs that run on it','They are the same thing','Hardware is only the screen; software is only the keyboard'],a:1,t:'Digital Devices',e:'Hardware = physical components (screen, keyboard, CPU). Software = programs and apps (games, browser, Word).'},
{id:'d03',q:'Which of these is an INPUT device?',o:['Speaker','Monitor (screen)','Printer','Keyboard'],a:3,t:'Digital Devices',e:'An input device sends information INTO the computer. A keyboard lets you type information in.'},
{id:'d04',q:'Which of these is an OUTPUT device?',o:['Microphone','Keyboard','Mouse','Printer'],a:3,t:'Digital Devices',e:'An output device receives information FROM the computer. A printer outputs a physical copy of a document.'},
{id:'d05',q:'What does a MONITOR do?',o:['It stores data permanently','It displays visual information from the computer on a screen','It connects the computer to the internet','It copies documents'],a:1,t:'Digital Devices',e:'A monitor is an output device that displays images, text and video from the computer.'},
{id:'d06',q:'A MICROPHONE is used to:',o:['Display images','Print documents','Input sound into a digital device','Store data'],a:2,t:'Digital Devices',e:'A microphone converts sound waves into digital signals — it is an input device for audio.'},
{id:'d07',q:'What does a TOUCHSCREEN allow you to do?',o:['Print documents only','Use your fingers to both input and interact with the screen directly','Listen to music','Take photographs only'],a:1,t:'Digital Devices',e:'A touchscreen is both an input AND output device — it displays information and lets you interact by touching the screen.'},
{id:'d08',q:'Which part of a computer stores information permanently, even when turned off?',o:['RAM (short-term memory)','The screen','The hard drive (storage)','The keyboard'],a:2,t:'Digital Devices',e:'A hard drive (or SSD) is permanent storage — it keeps data even when the computer is switched off.'},
{id:'d09',q:'What is the INTERNET?',o:['A type of computer program','A global network connecting millions of computers and devices','A social media app','A type of hard drive'],a:1,t:'Digital Devices',e:'The Internet is a worldwide network that connects billions of devices, allowing them to share information.'},
{id:'d10',q:'What does "WiFi" allow a device to do?',o:['Print without ink','Connect to the internet without a physical cable','Take better photographs','Store more data'],a:1,t:'Digital Devices',e:'WiFi is wireless networking technology — it allows devices to connect to the internet and other devices without cables.'},
{id:'d11',q:'Which of these is an example of SOFTWARE?',o:['The keyboard','The screen','A maths game app','The USB port'],a:2,t:'Digital Devices',e:'Software is programs and apps. A maths game app is software — it runs on the hardware.'},
{id:'d12',q:'What does pressing CTRL + S do in most programs on a computer?',o:['Select all text','Start a new document','Save the current file','Search for text'],a:2,t:'Digital Devices',e:'CTRL + S is the universal keyboard shortcut to save the current document or file.'},
{id:'d13',q:'A QR code is:',o:['A type of password','A scannable pattern that links to digital information or websites','A computer virus','A type of keyboard'],a:1,t:'Digital Devices',e:'A QR code is a 2D barcode. When scanned with a camera, it links to a website, video or other digital content.'},
{id:'d14',q:'What is an APP (application)?',o:['A physical button on a device','A software program designed for a specific purpose','A type of hardware','The internet itself'],a:1,t:'Digital Devices',e:'An app is a software program created for a specific task — like a camera app, calculator app or game.'},
{id:'d15',q:'Which device would Mevil use to VIDEO CALL his grandparents in another state?',o:['A printer','A scanner','A tablet or laptop with a camera','A hard drive'],a:2,t:'Digital Devices',e:'A tablet or laptop with a built-in camera and microphone can make video calls using apps like Zoom or FaceTime.'},

// ══ DATA & INFORMATION (VCDTDI015) ══

{id:'d16',q:'What is DATA?',o:['A type of computer program','Raw facts, numbers or symbols before they are given meaning','The physical parts of a computer','A type of internet connection'],a:1,t:'Data',e:'Data is raw facts and figures (numbers, words, images) before they are organised or analysed to create information.'},
{id:'d17',q:'Which of the following is an example of DIGITAL data?',o:['A handwritten note','A photo stored on a phone','A drawing on paper','A book from the library'],a:1,t:'Data',e:'Digital data is stored electronically. A photo on a phone is stored as digital data (binary numbers).'},
{id:'d18',q:'Computers store all information using only two digits: 0 and 1. This is called:',o:['Decimal code','Binary code','Alphabet code','Colour code'],a:1,t:'Data',e:'Binary code uses only 0s and 1s (off and on). All computer data is ultimately stored as sequences of 0s and 1s.'},
{id:'d19',q:'A SPREADSHEET program (like Microsoft Excel) is best used for:',o:['Writing stories and essays','Organising numbers and data in rows and columns','Watching videos','Drawing pictures'],a:1,t:'Data',e:'Spreadsheets organise data in rows and columns and can perform calculations automatically.'},
{id:'d20',q:'When you SEARCH for something using Google, you are:',o:['Creating new data','Deleting information','Accessing information stored on other computers','Printing a document'],a:2,t:'Data',e:'A search engine finds and retrieves information stored on computers (servers) connected to the internet.'},
{id:'d21',q:'What does it mean to SAVE a file on a computer?',o:['Delete it permanently','Print it on paper','Store it so it can be used later','Share it with friends'],a:2,t:'Data',e:'Saving stores your work in the computer\'s permanent memory (hard drive) so it remains after the program closes.'},
{id:'d22',q:'Which of these is an example of organising data into a PATTERN?',o:['Writing a random list of numbers','Sorting students into groups by their favourite colour','Drawing a picture','Sending an email'],a:1,t:'Data',e:'Sorting students by favourite colour organises the data into groups/patterns, making it easier to understand.'},
{id:'d23',q:'A DATABASE is best described as:',o:['A type of game','A physical filing cabinet only','An organised collection of information stored digitally','A type of internet connection'],a:2,t:'Data',e:'A database is an organised digital collection of information that can be easily searched, sorted and retrieved.'},
{id:'d24',q:'Pictures and symbols can be used to represent information. An example of this is:',o:['A blank page','A pictograph (picture graph) showing favourite foods','A random list of letters','A blank spreadsheet'],a:1,t:'Data',e:'A pictograph uses pictures/symbols to represent data — for example, a star symbol = 2 students.'},
{id:'d25',q:'What does "copy and paste" mean on a computer?',o:['Delete text and move it','Duplicate content and place it in a new location','Print text twice','Type the same thing twice'],a:1,t:'Data',e:'Copy (CTRL+C) duplicates selected content. Paste (CTRL+V) places the copy in a new location without removing the original.'},

// ══ ALGORITHMS & SEQUENCING (VCDTCD017) ══

{id:'d26',q:'An ALGORITHM is:',o:['A type of computer','A step-by-step set of instructions to solve a problem or complete a task','A website address','A keyboard shortcut'],a:1,t:'Algorithms',e:'An algorithm is a precise sequence of instructions that, when followed, solves a problem or achieves a goal.'},
{id:'d27',q:'Put these steps in the correct ORDER to brush your teeth: A) Rinse mouth  B) Put toothpaste on brush  C) Wet the brush  D) Brush teeth for 2 minutes',o:['A, B, C, D','C, B, D, A','B, D, C, A','D, C, B, A'],a:1,t:'Algorithms',e:'C (wet brush) → B (add toothpaste) → D (brush 2 min) → A (rinse). This is the logical sequence.'},
{id:'d28',q:'In programming, a LOOP is used to:',o:['Stop a program running','Repeat a set of instructions multiple times','Find errors in code','Connect to the internet'],a:1,t:'Algorithms',e:'A loop repeats a block of instructions a set number of times or until a condition is met, avoiding writing the same code repeatedly.'},
{id:'d29',q:'A CONDITIONAL instruction (IF...THEN) means:',o:['Always run these instructions','Only run these instructions if a condition is true','Never run these instructions','Run these instructions backwards'],a:1,t:'Algorithms',e:'IF it is raining THEN take an umbrella. The instruction only runs if the condition (rain) is true.'},
{id:'d30',q:'DEBUGGING means:',o:['Adding more features to a program','Removing insects from a computer','Finding and fixing errors (bugs) in a program','Deleting a program'],a:2,t:'Algorithms',e:'Bugs are errors in code that cause the program to behave incorrectly. Debugging is the process of finding and fixing them.'},
{id:'d31',q:'A robot is given these instructions: "Move forward 4 steps, turn left, move forward 3 steps." How many steps does it move in total?',o:['4','3','7','12'],a:2,t:'Algorithms',e:'4 forward + 3 forward = 7 steps total. (The turn is not a step — it just changes direction.)'},
{id:'d32',q:'In a flowchart, a DIAMOND shape represents:',o:['Start or end','A process or action','A decision (Yes/No question)','Data storage'],a:2,t:'Algorithms',e:'Diamond shapes in flowcharts show decision points — a yes/no question that leads to different paths.'},
{id:'d33',q:'Which of these is a real-life EXAMPLE of an algorithm?',o:['Watching TV randomly','A recipe with step-by-step cooking instructions','Sleeping','Talking to a friend'],a:1,t:'Algorithms',e:'A recipe is an algorithm — it gives precise step-by-step instructions to produce a result (a meal).'},
{id:'d34',q:'In Scratch (block-based coding), what does a "WHEN GREEN FLAG CLICKED" block do?',o:['Stops the program','Saves the project','Starts the program running','Makes the sprite disappear'],a:2,t:'Algorithms',e:'The green flag block is the START trigger. Clicking the green flag runs your Scratch program.'},
{id:'d35',q:'REPEAT 4 TIMES [draw one side of a shape, turn 90°]. What shape does this draw?',o:['Triangle','Circle','Hexagon','Square'],a:3,t:'Algorithms',e:'4 sides + 4 right-angle (90°) turns = a square. A square has 4 equal sides and 4 right angles.'},
{id:'d36',q:'What is wrong with this algorithm for making toast?\n1. Butter the toast\n2. Put bread in the toaster\n3. Wait for it to pop up',o:['Step 3 is missing','The steps are in the wrong order','There are too many steps','Nothing is wrong'],a:1,t:'Algorithms',e:'You cannot butter toast before it is toasted. The correct order: put bread in → wait for it to pop → butter.'},
{id:'d37',q:'A program counts from 1 to 5. It uses: REPEAT 5 TIMES [print the number, add 1]. This is an example of:',o:['A conditional','A loop','A bug','Debugging'],a:1,t:'Algorithms',e:'Repeating the same instruction (print, add 1) multiple times is a loop.'},
{id:'d38',q:'IF the temperature is below 10°C THEN wear a jumper. On a 15°C Melbourne morning, what happens?',o:['You wear a jumper','You do not wear a jumper','The computer crashes','Nothing can be determined'],a:1,t:'Algorithms',e:'The temperature (15°C) is NOT below 10°C, so the condition is false — no jumper is worn.'},
{id:'d39',q:'In a coding game, a sprite needs to move right 3 times then up 2 times. How many TOTAL moves?',o:['2','3','5','6'],a:2,t:'Algorithms',e:'3 moves right + 2 moves up = 5 total moves.'},
{id:'d40',q:'What is PSEUDOCODE?',o:['A made-up programming language for beginners','Code written in English-like words to plan a program before coding it','A type of bug','A type of hardware'],a:1,t:'Algorithms',e:'Pseudocode is an informal description of a program\'s steps in plain language — used to plan before writing real code.'},
{id:'d41',q:'A robot vacuum cleaner is programmed to: "Move forward until you hit a wall, then turn right." This is an example of:',o:['Saving data','A conditional loop (IF wall THEN turn)','Deleting files','Printing a document'],a:1,t:'Algorithms',e:'This is a conditional instruction — the robot checks (IF wall) and responds accordingly (THEN turn right).'},
{id:'d42',q:'In block-based coding, which block would make a sprite say "Hello" for 2 seconds?',o:['Move 10 steps','Say Hello for 2 seconds','Play sound until done','Change colour'],a:1,t:'Algorithms',e:'"Say Hello for 2 seconds" is a specific output block that makes the sprite display a speech bubble with the word Hello.'},
{id:'d43',q:'What does it mean when a computer PROGRAM CRASHES?',o:['The computer falls off the table','The program stops working properly and closes unexpectedly','The computer runs out of battery','The internet disconnects'],a:1,t:'Algorithms',e:'A crash means the program encounters an error it cannot handle and stops working — often due to a bug in the code.'},

// ══ ONLINE SAFETY (VCDTCD019) ══

{id:'d44',q:'Someone you only know online asks for your home address. You should:',o:['Give it to them — they seem nice','Post it in a comment so others can visit too','Never share it — tell a trusted adult','Only share your suburb, not your street'],a:2,t:'Online Safety',e:'NEVER share your home address online. Tell a trusted adult (parent, teacher) if anyone online asks for personal information.'},
{id:'d45',q:'Which is the STRONGEST password?',o:['mevil','123456','Mevil2015!','password'],a:2,t:'Online Safety',e:'A strong password mixes upper and lowercase letters, numbers and symbols. "Mevil2015!" is much harder to guess than simple words or numbers.'},
{id:'d46',q:'What is CYBERBULLYING?',o:['Playing games online with friends','Bullying someone using technology such as messages or social media','Searching the internet for information','Creating a website'],a:1,t:'Online Safety',e:'Cyberbullying is bullying that takes place online or through digital devices — texts, social media posts, online games, etc.'},
{id:'d47',q:'If you see something online that makes you feel scared or uncomfortable, you should:',o:['Keep it secret and close the browser','Click on it to find out more','Tell a trusted adult immediately','Send it to your friends'],a:2,t:'Online Safety',e:'Always tell a trusted adult (parent, teacher) if you see upsetting or inappropriate content online. Never keep it secret.'},
{id:'d48',q:'Should you share your password with your best friend?',o:['Yes — best friends can be trusted','Yes — only if they promise to keep it secret','No — passwords should always be kept private','Only share it once'],a:2,t:'Online Safety',e:'Passwords should NEVER be shared — even with close friends. Sharing passwords puts your accounts at risk.'},
{id:'d49',q:'A padlock icon (🔒) in a website address bar means:',o:['The website is broken','The website uses a secure, encrypted connection (HTTPS)','You need a password to view the page','The website is about locks'],a:1,t:'Online Safety',e:'HTTPS with a padlock means the connection between your browser and the website is encrypted and more secure.'},
{id:'d50',q:'What is SPAM email?',o:['Important emails from school','Emails from family members','Unwanted junk emails, often trying to trick you','Emails with photographs'],a:2,t:'Online Safety',e:'Spam is unsolicited bulk email — often advertising, scams or phishing attempts trying to trick you into clicking links.'},
{id:'d51',q:'Before posting a photo of a friend online, you should:',o:['Post it as quickly as possible','Ask your friend and their parents for permission first','Send it to everyone in your contact list','Only post it on public websites'],a:1,t:'Online Safety',e:'Always ask permission before sharing photos of others online. Even with friends, it is respectful and important for privacy.'},
{id:'d52',q:'Which rule helps keep you safe when playing online games?',o:['Give your real name to other players so they can find you','Meet other players in person as soon as possible','Only play with people you know in real life, or keep game chat friendly','Share your home suburb so friends can visit'],a:2,t:'Online Safety',e:'Only play with people you know in real life, or keep online interactions to in-game chat without sharing personal details.'},
{id:'d53',q:'What does "SCREEN TIME" mean?',o:['The size of your computer screen','The amount of time spent using digital devices (phones, tablets, computers)','The brightness setting on a screen','The type of screen on a device'],a:1,t:'Online Safety',e:'Screen time refers to the total amount of time spent looking at and using digital screens.'},
{id:'d54',q:'Why is it important to LOG OUT of a shared computer when you finish?',o:['To make the computer faster','To stop others from accessing your account and personal information','To delete your files','To save the computer\'s battery'],a:1,t:'Online Safety',e:'Logging out prevents other users of a shared computer from accessing your accounts, files and personal information.'},
{id:'d55',q:'A person online claims to be a 9-year-old student but asks strange questions about where you live. You should:',o:['Answer all their questions politely','Trust them because they say they are a child','Stop talking to them and tell a trusted adult','Ask them to prove they are really 9'],a:2,t:'Online Safety',e:'People online can pretend to be someone they are not. Stop the conversation and tell a trusted adult if anything feels wrong.'},
{id:'d56',q:'Which of these is PERSONAL INFORMATION you should NOT share online?',o:['Your favourite colour','Your favourite AFL team','Your school name and home address','Your favourite subject'],a:2,t:'Online Safety',e:'Your school name and address are personal details that could be used by strangers to find you. Never share them online.'},
{id:'d57',q:'If a pop-up message appears saying "You have won a prize! Click here!", what should you do?',o:['Click it immediately to claim your prize','Share it with friends so they can win too','Close it — it is almost certainly a scam','Enter your details to receive the prize'],a:2,t:'Online Safety',e:'Prize pop-ups are almost always scams designed to steal your personal information or install harmful software. Always close them.'},

// ── Mixed Digital Tech Review ──
{id:'d58',q:'What does "drag and drop" mean on a computer?',o:['Typing text quickly','Clicking and holding an item, moving it, then releasing it in a new location','Deleting a file','Copying text'],a:1,t:'Digital Devices',e:'Drag and drop: click + hold on an item, move it to the new position, release to drop it there.'},
{id:'d59',q:'What is a FOLDER on a computer?',o:['A physical binder for papers','A way to organise and store related files together on a computer','A type of program','An internet browser'],a:1,t:'Data',e:'A folder is a container that organises related files together — just like a physical folder holds related papers.'},
{id:'d60',q:'What does CTRL + Z do on most computers?',o:['Save the file','Undo the last action','Select all','Copy the text'],a:1,t:'Digital Devices',e:'CTRL + Z undoes the last action — it reverses what you just did, which is very helpful when you make a mistake.'},
{id:'d61',q:'In coding, a VARIABLE is like:',o:['A type of loop','A labelled box that stores a value that can change','A type of error','The end of a program'],a:1,t:'Algorithms',e:'A variable stores a value (like a number or word) that a program can use and change — like a labelled box: score = 10.'},
{id:'d62',q:'What is the purpose of a WEB BROWSER?',o:['To create documents','To access and navigate websites on the internet','To store photos','To send emails'],a:1,t:'Digital Devices',e:'A web browser (Chrome, Safari, Firefox) is software that lets you find, access and display web pages on the internet.'},
{id:'d63',q:'A digital clock displays 14:30. In 12-hour time this is:',o:['4:30 am','2:30 pm','12:30 pm','4:30 pm'],a:1,t:'Data',e:'14:30 in 24-hour time = 14 − 12 = 2, so 2:30 pm. Afternoon times: subtract 12 from the hour.'},
{id:'d64',q:'Mevil creates a presentation with pictures and words about koalas. Which type of software is he MOST LIKELY using?',o:['A music app','A presentation program (like PowerPoint or Google Slides)','A calculator','A video game'],a:1,t:'Digital Devices',e:'Presentation software (PowerPoint, Google Slides, Keynote) lets you create slides with text, images and animations.'},
{id:'d65',q:'Which action is MOST RESPONSIBLE when using technology at school?',o:['Playing games instead of completing work','Using the internet to find useful information for a project','Sharing your login details with a classmate','Watching videos unrelated to school'],a:1,t:'Online Safety',e:'Responsible technology use means using devices for their intended purpose — such as researching and completing schoolwork.'},
{id:'d66',q:'What does "COPY" (CTRL+C) do to selected text?',o:['Deletes the text permanently','Creates a duplicate that can be pasted elsewhere, leaving the original','Moves the text to a new location','Changes the font'],a:1,t:'Digital Devices',e:'COPY creates a duplicate of the selected content. The original stays in place and the copy can be pasted elsewhere.'},
{id:'d67',q:'A robot is given: IF battery < 10% THEN return to charger. This is an example of:',o:['A loop','A conditional (IF/THEN) statement','A bug','An output'],a:1,t:'Algorithms',e:'IF/THEN is a conditional statement. The robot only returns to the charger IF the battery level meets the condition (below 10%).'},
{id:'d68',q:'Which word BEST describes data that is organised and meaningful?',o:['Raw data','Random data','Information','Binary'],a:2,t:'Data',e:'When raw data is organised and given context, it becomes information — something meaningful that helps us understand something.'},
{id:'d69',q:'What is an EMAIL?',o:['A letter sent by regular post','A digital message sent electronically via the internet','A phone call','A social media post'],a:1,t:'Digital Devices',e:'Email (electronic mail) is a digital message sent from one person to another through the internet.'},
{id:'d70',q:'Mevil finishes using the school iPad. What should he do before putting it away?',o:['Leave all apps open so he can continue next time','Delete all the apps','Close all apps and log out of his account','Leave it on so it is ready for the next person'],a:2,t:'Online Safety',e:'Always close apps and log out when finished with a shared device. This protects your privacy and the device\'s battery.'},
];
