window.QB = window.QB || {};

/* ============================================================
   NAPLAN NUMERACY  –  64 questions  (32Q / test)
   Year 2 warm-up level | Victorian Curriculum VCMNA / VCMMG / VCMSP
   ============================================================ */
window.QB.naplan_num = [

  /* ── Place Value ── */
  {id:'n01',q:'What is the value of the digit 5 in the number 52?',
   o:['5','50','500','5000'],a:1,t:'Place Value',e:'The 5 is in the tens place, so its value is 50.'},
  {id:'n02',q:'Which number has a 3 in the tens place?',
   o:['13','31','301','130'],a:1,t:'Place Value',e:'31 = 3 tens and 1 one. The 3 is in the tens place.'},
  {id:'n03',q:'What number is shown by 4 tens and 7 ones?',
   o:['47','74','407','470'],a:0,t:'Place Value',e:'4 tens = 40, plus 7 ones = 47.'},
  {id:'n04',q:'Which number is between 60 and 70?',
   o:['56','65','76','16'],a:1,t:'Place Value',e:'65 lies between 60 and 70.'},
  {id:'n05',q:'What is the largest number you can make with the digits 3, 7 and 1?',
   o:['137','173','317','731'],a:3,t:'Place Value',e:'Put the largest digit first: 7, then 3, then 1 → 731.'},
  {id:'n06',q:'Which is greater: 89 or 98?',
   o:['89','98','They are the same','Cannot tell'],a:1,t:'Place Value',e:'98 > 89 because 9 tens > 8 tens.'},
  {id:'n07',q:'How many tens are in the number 70?',
   o:['0','7','70','17'],a:1,t:'Place Value',e:'70 = 7 tens and 0 ones.'},
  {id:'n08',q:'What number comes just before 100?',
   o:['99','101','90','109'],a:0,t:'Place Value',e:'99 is one less than 100.'},
  {id:'n09',q:'Sam writes the number ninety-four. Which number did Sam write?',
   o:['49','904','409','94'],a:3,t:'Place Value',e:'Ninety-four = 9 tens and 4 ones = 94.'},
  {id:'n10',q:'Order these numbers from smallest to largest: 45, 54, 14, 41.',
   o:['14, 41, 45, 54','54, 45, 41, 14','14, 45, 41, 54','41, 14, 45, 54'],a:0,t:'Place Value',
   e:'Start with 14 (smallest), then 41, 45, 54 (largest).'},

  /* ── Addition & Subtraction ── */
  {id:'n11',q:'What is 36 + 25?',
   o:['51','61','71','611'],a:1,t:'Addition',e:'36 + 25 = 61. Add ones first: 6+5=11 (write 1, carry 1). Then tens: 3+2+1=6. Answer: 61.'},
  {id:'n12',q:'What is 54 − 18?',
   o:['26','36','46','72'],a:1,t:'Subtraction',e:'54 − 18 = 36. Borrow from tens: 14−8=6 ones, 4−1=3 tens → 36.'},
  {id:'n13',q:'Mevil had 47 stickers. He gave 19 to his friend. How many stickers does he have now?',
   o:['28','38','66','26'],a:0,t:'Subtraction',e:'47 − 19 = 28. Think: 47 − 20 + 1 = 27 + 1 = 28.'},
  {id:'n14',q:'What is 29 + 43?',
   o:['62','72','71','63'],a:1,t:'Addition',e:'29 + 43 = 72. 29 + 40 = 69, 69 + 3 = 72.'},
  {id:'n15',q:'There are 32 birds in a tree. 15 fly away. How many are left?',
   o:['47','17','27','13'],a:1,t:'Subtraction',e:'32 − 15 = 17.'},
  {id:'n16',q:'What number goes in the box? □ + 14 = 30',
   o:['14','16','44','18'],a:1,t:'Addition',e:'30 − 14 = 16. So the missing number is 16.'},
  {id:'n17',q:'Maya scored 24 points in her first game and 38 in her second. What is her total?',
   o:['52','62','14','614'],a:1,t:'Addition',e:'24 + 38 = 62. 24 + 38: 20+30=50, 4+8=12, 50+12=62.'},
  {id:'n18',q:'What is 80 − 37?',
   o:['43','53','47','33'],a:0,t:'Subtraction',e:'80 − 37 = 43. 80 − 40 = 40, 40 + 3 = 43.'},
  {id:'n19',q:'Which two numbers add to make 50?',
   o:['28 + 21','33 + 17','24 + 14','19 + 30'],a:1,t:'Addition',e:'33 + 17 = 50.'},
  {id:'n20',q:'A box holds 75 pencils. 28 are taken out. How many pencils remain?',
   o:['47','53','57','103'],a:0,t:'Subtraction',e:'75 − 28 = 47. 75 − 30 = 45, 45 + 2 = 47.'},

  /* ── Multiplication & Division ── */
  {id:'n21',q:'What is 5 × 4?',
   o:['9','20','25','40'],a:1,t:'Multiplication',e:'5 groups of 4 = 4+4+4+4+4 = 20.'},
  {id:'n22',q:'There are 3 bags with 6 apples each. How many apples in total?',
   o:['9','12','18','36'],a:2,t:'Multiplication',e:'3 × 6 = 18.'},
  {id:'n23',q:'What is 12 ÷ 3?',
   o:['3','4','5','6'],a:1,t:'Division',e:'12 ÷ 3 = 4 (3 goes into 12 four times).'},
  {id:'n24',q:'Which is the same as 4 + 4 + 4?',
   o:['4 × 3','4 × 4','3 × 3','3 + 4'],a:0,t:'Multiplication',e:'3 groups of 4 = 4 × 3 = 12.'},
  {id:'n25',q:'20 strawberries are shared equally among 4 friends. How many does each friend get?',
   o:['4','5','10','16'],a:1,t:'Division',e:'20 ÷ 4 = 5.'},
  {id:'n26',q:'What is 2 × 9?',
   o:['11','16','18','20'],a:2,t:'Multiplication',e:'2 × 9 = 18.'},
  {id:'n27',q:'Skip-count by 5s. What comes next: 15, 20, 25, ___?',
   o:['28','30','35','20'],a:1,t:'Multiplication',e:'Count by 5s: 25 + 5 = 30.'},
  {id:'n28',q:'There are 5 rows of seats with 6 seats in each row. How many seats in total?',
   o:['11','25','30','36'],a:2,t:'Multiplication',e:'5 × 6 = 30.'},

  /* ── Fractions ── */
  {id:'n29',q:'A pizza is cut into 4 equal pieces. Mia eats one piece. What fraction did she eat?',
   o:['1/2','1/3','1/4','2/4'],a:2,t:'Fractions',e:'One piece out of four equal pieces = one quarter = 1/4.'},
  {id:'n30',q:'Which fraction is the same as a half?',
   o:['1/4','2/4','3/4','1/3'],a:1,t:'Fractions',e:'2/4 = 1/2 (both mean equal halves of a whole).'},
  {id:'n31',q:'A ribbon is cut into 3 equal parts. What fraction is each part?',
   o:['1/2','1/3','1/4','2/3'],a:1,t:'Fractions',e:'3 equal parts → each part is one third = 1/3.'},
  {id:'n32',q:'Which shape shows 3/4 shaded? (Think: 4 equal parts, 3 are shaded.)',
   o:['1 of 4 parts shaded','2 of 4 parts shaded','3 of 4 parts shaded','4 of 4 parts shaded'],a:2,t:'Fractions',
   e:'3 out of 4 equal parts shaded = 3/4.'},

  /* ── Money ── */
  {id:'n33',q:'How much is 2 fifty-cent coins worth?',
   o:['50c','$1.00','$1.50','$2.00'],a:1,t:'Money',e:'50c + 50c = $1.00.'},
  {id:'n34',q:'Jake buys a mango for $1.50. He pays with a $2 coin. How much change does he get?',
   o:['50c','$1.50','$3.50','$1.00'],a:0,t:'Money',e:'$2.00 − $1.50 = $0.50 = 50 cents.'},
  {id:'n35',q:'A toy costs $4.25. Which coins could you use to pay the exact amount?',
   o:['4 one-dollar coins','$4 and 1 twenty-cent and 1 five-cent coin','$5 coin','2 two-dollar coins'],a:1,
   t:'Money',e:'$4.00 + 20c + 5c = $4.25.'},
  {id:'n36',q:'Lena has three $2 coins. How much money does she have?',
   o:['$2','$4','$6','$8'],a:2,t:'Money',e:'3 × $2 = $6.'},

  /* ── Measurement – Length ── */
  {id:'n37',q:'Which unit would you use to measure the length of a pencil?',
   o:['kilometres','metres','centimetres','tonnes'],a:2,t:'Measurement',e:'A pencil is about 15–20 cm. Centimetres are the right unit.'},
  {id:'n38',q:'A ruler is 30 cm long. Two rulers placed end-to-end are how long?',
   o:['30 cm','45 cm','60 cm','90 cm'],a:2,t:'Measurement',e:'30 + 30 = 60 cm.'},
  {id:'n39',q:'Toby\'s desk is 1 metre wide. His book is 30 cm wide. How much wider is the desk?',
   o:['30 cm','70 cm','130 cm','1 m 30 cm'],a:1,t:'Measurement',e:'100 cm − 30 cm = 70 cm.'},

  /* ── Measurement – Time ── */
  {id:'n40',q:'How many minutes are in one hour?',
   o:['24','30','60','100'],a:2,t:'Time',e:'There are 60 minutes in one hour.'},
  {id:'n41',q:'School starts at 9:00 am and finishes at 3:30 pm. How long is the school day?',
   o:['5 hours','5 hours 30 minutes','6 hours','6 hours 30 minutes'],a:3,t:'Time',
   e:'9:00 am to 3:00 pm = 6 hours. Plus 30 min = 6 hours 30 minutes.'},
  {id:'n42',q:'The clock shows quarter past 2. What time is this?',
   o:['2:05','2:15','2:25','2:45'],a:1,t:'Time',e:'Quarter past = 15 minutes past the hour. So 2:15.'},
  {id:'n43',q:'Today is Tuesday. What day was yesterday?',
   o:['Sunday','Monday','Wednesday','Thursday'],a:1,t:'Time',e:'The day before Tuesday is Monday.'},

  /* ── Measurement – Mass & Capacity ── */
  {id:'n44',q:'Which is heavier: 1 kilogram of feathers or 1 kilogram of rocks?',
   o:['feathers','rocks','they weigh the same','cannot tell'],a:2,t:'Measurement',
   e:'1 kg of feathers = 1 kg of rocks. The mass is the same even if the volume differs.'},
  {id:'n45',q:'A bucket holds 8 litres. You fill it with 3 litres. How many more litres are needed to fill it?',
   o:['3','5','8','11'],a:1,t:'Measurement',e:'8 − 3 = 5 litres more needed.'},

  /* ── Geometry ── */
  {id:'n46',q:'How many sides does a hexagon have?',
   o:['4','5','6','8'],a:2,t:'Geometry',e:'A hexagon has 6 sides.'},
  {id:'n47',q:'Which 3D shape has 6 flat square faces?',
   o:['Sphere','Cone','Cylinder','Cube'],a:3,t:'Geometry',e:'A cube has 6 equal square faces.'},
  {id:'n48',q:'A triangle has 3 sides. What is the total number of sides in 4 triangles?',
   o:['7','9','12','16'],a:2,t:'Geometry',e:'4 × 3 = 12 sides.'},
  {id:'n49',q:'Which shape has no flat faces and no corners?',
   o:['Cube','Cone','Sphere','Cylinder'],a:2,t:'Geometry',e:'A sphere is completely round — no flat faces, no corners.'},
  {id:'n50',q:'How many corners (vertices) does a rectangle have?',
   o:['2','3','4','6'],a:2,t:'Geometry',e:'A rectangle has 4 corners (vertices).'},

  /* ── Patterns & Algebra ── */
  {id:'n51',q:'What is the missing number? 7, 14, 21, ___, 35',
   o:['24','25','28','29'],a:2,t:'Patterns',e:'The pattern is +7. 21 + 7 = 28.'},
  {id:'n52',q:'Which rule describes the pattern 2, 4, 6, 8, 10?',
   o:['Add 1','Add 2','Multiply by 2','Subtract 2'],a:1,t:'Patterns',e:'Each number increases by 2 (counting by 2s).'},
  {id:'n53',q:'What comes next in this pattern: 100, 90, 80, 70, ___?',
   o:['50','55','60','65'],a:2,t:'Patterns',e:'The pattern is −10. 70 − 10 = 60.'},
  {id:'n54',q:'Find the missing number: 5 + ___ = 13',
   o:['5','7','8','9'],a:2,t:'Patterns',e:'13 − 5 = 8. The missing number is 8.'},

  /* ── Data & Graphs ── */
  {id:'n55',q:'A class voted for their favourite fruit. Apples got 8 votes, Bananas 5, Mangoes 7. How many votes in total?',
   o:['13','15','20','22'],a:2,t:'Data',e:'8 + 5 + 7 = 20 total votes.'},
  {id:'n56',q:'In a column graph, the Maths bar reaches 9 and the English bar reaches 6. How many more students chose Maths?',
   o:['2','3','5','15'],a:1,t:'Data',e:'9 − 6 = 3 more students chose Maths.'},
  {id:'n57',q:'6 students each collected 4 cans for recycling. How many cans in total?',
   o:['10','16','24','42'],a:2,t:'Data',e:'6 × 4 = 24 cans.'},
  {id:'n58',q:'A tally chart shows 5 birds on Monday, 3 on Tuesday, 7 on Wednesday. Which day had the most birds?',
   o:['Monday','Tuesday','Wednesday','All the same'],a:2,t:'Data',e:'Wednesday had 7 birds — the most.'},

  /* ── Problem Solving ── */
  {id:'n59',q:'Ben has $10. He spends $3.50 on a snack. How much money does he have left?',
   o:['$6.00','$6.50','$7.00','$7.50'],a:1,t:'Problem Solving',e:'$10.00 − $3.50 = $6.50.'},
  {id:'n60',q:'A loaf of bread is cut into 8 equal slices. Mevil eats 3 slices. What fraction is left?',
   o:['3/8','5/8','3/5','1/2'],a:1,t:'Problem Solving',e:'8 − 3 = 5 slices left. Fraction left = 5/8.'},
  {id:'n61',q:'Emma runs 200 m, then walks 150 m. How far did she travel altogether?',
   o:['300 m','350 m','400 m','450 m'],a:1,t:'Problem Solving',e:'200 + 150 = 350 m.'},
  {id:'n62',q:'A class of 28 students is split into 4 equal groups. How many students are in each group?',
   o:['5','6','7','8'],a:2,t:'Problem Solving',e:'28 ÷ 4 = 7 students per group.'},
  {id:'n63',q:'Zara has 3 boxes of 10 crayons and 5 loose crayons. How many crayons altogether?',
   o:['15','30','35','53'],a:2,t:'Problem Solving',e:'3 × 10 = 30, plus 5 = 35 crayons.'},
  {id:'n64',q:'A garden has 6 rows of tomatoes with 8 plants in each row. How many tomato plants are there?',
   o:['14','36','48','64'],a:2,t:'Problem Solving',e:'6 × 8 = 48 tomato plants.'}
];

/* ============================================================
   NAPLAN READING  –  62 questions  (40Q / test)
   Year 2 warm-up level | Victorian Curriculum VCELY / VCELA / VCELT
   Passages are in the 'p' field; comprehension follows.
   ============================================================ */
window.QB.naplan_read = [

  /* ── PASSAGE 1: Koalas ── */
  {id:'r01',
   p:'Koalas are Australian animals. They live in eucalyptus trees and eat the leaves. Koalas sleep for up to 18 hours a day. They are not bears, even though many people call them "koala bears." A baby koala is called a joey. A joey lives in its mother\'s pouch until it is big enough to climb on its mother\'s back.',
   q:'Where do koalas live?',
   o:['In burrows underground','In eucalyptus trees','Near rivers and lakes','In open grassland'],a:1,t:'Reading Comprehension',
   e:'The passage says koalas live in eucalyptus trees.'},
  {id:'r02',
   p:'Koalas are Australian animals. They live in eucalyptus trees and eat the leaves. Koalas sleep for up to 18 hours a day. They are not bears, even though many people call them "koala bears." A baby koala is called a joey. A joey lives in its mother\'s pouch until it is big enough to climb on its mother\'s back.',
   q:'How long can koalas sleep each day?',
   o:['8 hours','12 hours','18 hours','24 hours'],a:2,t:'Reading Comprehension',
   e:'The passage says koalas sleep for up to 18 hours a day.'},
  {id:'r03',
   p:'Koalas are Australian animals. They live in eucalyptus trees and eat the leaves. Koalas sleep for up to 18 hours a day. They are not bears, even though many people call them "koala bears." A baby koala is called a joey. A joey lives in its mother\'s pouch until it is big enough to climb on its mother\'s back.',
   q:'What is a baby koala called?',
   o:['A cub','A pup','A joey','A kitten'],a:2,t:'Reading Comprehension',
   e:'The passage states a baby koala is called a joey.'},
  {id:'r04',
   p:'Koalas are Australian animals. They live in eucalyptus trees and eat the leaves. Koalas sleep for up to 18 hours a day. They are not bears, even though many people call them "koala bears." A baby koala is called a joey. A joey lives in its mother\'s pouch until it is big enough to climb on its mother\'s back.',
   q:'Why is it wrong to call a koala a "koala bear"?',
   o:['Because koalas are too small to be bears','Because koalas are not bears','Because koalas do not live in forests','Because koalas are only found in zoos'],
   a:1,t:'Reading Comprehension',e:'The passage says koalas are not bears, even though people call them "koala bears."'},
  {id:'r05',
   p:'Koalas are Australian animals. They live in eucalyptus trees and eat the leaves. Koalas sleep for up to 18 hours a day. They are not bears, even though many people call them "koala bears." A baby koala is called a joey. A joey lives in its mother\'s pouch until it is big enough to climb on its mother\'s back.',
   q:'Where does a joey live when it is very young?',
   o:['In a nest in a tree','In a burrow in the ground','In its mother\'s pouch','On its mother\'s back'],
   a:2,t:'Reading Comprehension',e:'A joey lives in its mother\'s pouch until it is big enough to ride on its mother\'s back.'},

  /* ── PASSAGE 2: Recycling at School ── */
  {id:'r06',
   p:'Our school started a recycling programme this term. Students bring plastic bottles and paper to school. We put the paper in the blue bin and the plastic in the yellow bin. Every Friday, the bins are collected by a recycling truck. Recycling helps keep our parks and beaches clean. It also saves energy and helps protect animals that might eat rubbish.',
   q:'What does the school put in the blue bin?',
   o:['Glass','Plastic bottles','Paper','Food scraps'],a:2,t:'Reading Comprehension',
   e:'The passage says paper goes in the blue bin.'},
  {id:'r07',
   p:'Our school started a recycling programme this term. Students bring plastic bottles and paper to school. We put the paper in the blue bin and the plastic in the yellow bin. Every Friday, the bins are collected by a recycling truck. Recycling helps keep our parks and beaches clean. It also saves energy and helps protect animals that might eat rubbish.',
   q:'When are the bins collected?',
   o:['Every Monday','Every Wednesday','Every Friday','Every Sunday'],a:2,t:'Reading Comprehension',
   e:'The passage says the bins are collected every Friday.'},
  {id:'r08',
   p:'Our school started a recycling programme this term. Students bring plastic bottles and paper to school. We put the paper in the blue bin and the plastic in the yellow bin. Every Friday, the bins are collected by a recycling truck. Recycling helps keep our parks and beaches clean. It also saves energy and helps protect animals that might eat rubbish.',
   q:'Which of these is a reason recycling is important according to the passage?',
   o:['It makes school cheaper','It saves energy','It gives students extra time','It fills up trucks quickly'],
   a:1,t:'Reading Comprehension',e:'The passage says recycling saves energy and helps protect animals.'},
  {id:'r09',
   p:'Our school started a recycling programme this term. Students bring plastic bottles and paper to school. We put the paper in the blue bin and the plastic in the yellow bin. Every Friday, the bins are collected by a recycling truck. Recycling helps keep our parks and beaches clean. It also saves energy and helps protect animals that might eat rubbish.',
   q:'What type of text is this passage?',
   o:['A poem','A story about an animal','An information report','A personal diary'],
   a:2,t:'Text Type',e:'The passage gives facts about a recycling programme — it is an information report.'},

  /* ── PASSAGE 3: A Letter from Camp ── */
  {id:'r10',
   p:'Dear Mum and Dad,\nI am having a great time at camp! Yesterday we went canoeing on the river. I was nervous at first but then it was really fun. We also saw a kookaburra sitting in a gum tree. It laughed at us! Tonight we are having a campfire and toasting marshmallows. I cannot wait!\nLove, Mevil',
   q:'What activity did Mevil do on the river?',
   o:['Swimming','Canoeing','Fishing','Kayaking'],a:1,t:'Reading Comprehension',
   e:'The letter says "we went canoeing on the river."'},
  {id:'r11',
   p:'Dear Mum and Dad,\nI am having a great time at camp! Yesterday we went canoeing on the river. I was nervous at first but then it was really fun. We also saw a kookaburra sitting in a gum tree. It laughed at us! Tonight we are having a campfire and toasting marshmallows. I cannot wait!\nLove, Mevil',
   q:'How did Mevil feel before the canoeing started?',
   o:['Excited','Angry','Nervous','Sad'],a:2,t:'Reading Comprehension',
   e:'Mevil says "I was nervous at first."'},
  {id:'r12',
   p:'Dear Mum and Dad,\nI am having a great time at camp! Yesterday we went canoeing on the river. I was nervous at first but then it was really fun. We also saw a kookaburra sitting in a gum tree. It laughed at us! Tonight we are having a campfire and toasting marshmallows. I cannot wait!\nLove, Mevil',
   q:'What type of text is this?',
   o:['A newspaper article','A personal letter','An information report','A recipe'],
   a:1,t:'Text Type',e:'The text starts with "Dear Mum and Dad" and ends with "Love, Mevil" — it is a personal letter.'},
  {id:'r13',
   p:'Dear Mum and Dad,\nI am having a great time at camp! Yesterday we went canoeing on the river. I was nervous at first but then it was really fun. We also saw a kookaburra sitting in a gum tree. It laughed at us! Tonight we are having a campfire and toasting marshmallows. I cannot wait!\nLove, Mevil',
   q:'What bird did they see at camp?',
   o:['Galah','Kookaburra','Pelican','Magpie'],a:1,t:'Reading Comprehension',
   e:'The letter mentions seeing a kookaburra in a gum tree.'},

  /* ── PASSAGE 4: How Seeds Grow ── */
  {id:'r14',
   p:'Plants grow from seeds. First, you plant a seed in soil. The seed needs water and sunlight to grow. After a few days, a small shoot pushes up through the soil. The shoot grows leaves and reaches toward the light. Over time it becomes a full-grown plant. Some plants grow flowers. The flowers make more seeds so the cycle can start again.',
   q:'What is the first step in growing a plant?',
   o:['Watering the plant','Planting a seed in soil','Waiting for flowers','Giving the plant sunlight'],
   a:1,t:'Reading Comprehension',e:'The passage says "First, you plant a seed in soil."'},
  {id:'r15',
   p:'Plants grow from seeds. First, you plant a seed in soil. The seed needs water and sunlight to grow. After a few days, a small shoot pushes up through the soil. The shoot grows leaves and reaches toward the light. Over time it becomes a full-grown plant. Some plants grow flowers. The flowers make more seeds so the cycle can start again.',
   q:'What does a seed need to grow?',
   o:['Water and sunlight','Just water','Just sunlight','Lots of wind'],
   a:0,t:'Reading Comprehension',e:'The passage says seeds need water and sunlight to grow.'},
  {id:'r16',
   p:'Plants grow from seeds. First, you plant a seed in soil. The seed needs water and sunlight to grow. After a few days, a small shoot pushes up through the soil. The shoot grows leaves and reaches toward the light. Over time it becomes a full-grown plant. Some plants grow flowers. The flowers make more seeds so the cycle can start again.',
   q:'Why do flowers make seeds?',
   o:['To attract butterflies','So the cycle can start again','To make fruit to eat','To protect the plant'],
   a:1,t:'Reading Comprehension',e:'The passage says flowers make more seeds "so the cycle can start again."'},
  {id:'r17',
   p:'Plants grow from seeds. First, you plant a seed in soil. The seed needs water and sunlight to grow. After a few days, a small shoot pushes up through the soil. The shoot grows leaves and reaches toward the light. Over time it becomes a full-grown plant. Some plants grow flowers. The flowers make more seeds so the cycle can start again.',
   q:'What pushes up through the soil?',
   o:['A root','A flower','A shoot','A leaf'],a:2,t:'Reading Comprehension',
   e:'The passage says "a small shoot pushes up through the soil."'},

  /* ── PASSAGE 5: Melbourne Weather ── */
  {id:'r18',
   p:'Melbourne is famous for having four seasons in one day. In summer, the weather can be very hot — sometimes over 40°C. Winters are cool and sometimes rainy. Spring brings flowers and warm breezes. Autumn is when leaves on trees turn red, orange and yellow and fall to the ground. Melbourne people always carry an umbrella just in case!',
   q:'What is Melbourne famous for?',
   o:['Its hot weather all year','Having four seasons in one day','Never raining','Being near the beach'],
   a:1,t:'Reading Comprehension',e:'The passage says Melbourne is famous for "having four seasons in one day."'},
  {id:'r19',
   p:'Melbourne is famous for having four seasons in one day. In summer, the weather can be very hot — sometimes over 40°C. Winters are cool and sometimes rainy. Spring brings flowers and warm breezes. Autumn is when leaves on trees turn red, orange and yellow and fall to the ground. Melbourne people always carry an umbrella just in case!',
   q:'What happens to leaves on trees in autumn?',
   o:['They grow bigger','They turn green and stay on the tree','They turn red, orange and yellow and fall','They catch fire in the heat'],
   a:2,t:'Reading Comprehension',e:'The passage says autumn leaves turn red, orange and yellow and fall to the ground.'},
  {id:'r20',
   p:'Melbourne is famous for having four seasons in one day. In summer, the weather can be very hot — sometimes over 40°C. Winters are cool and sometimes rainy. Spring brings flowers and warm breezes. Autumn is when leaves on trees turn red, orange and yellow and fall to the ground. Melbourne people always carry an umbrella just in case!',
   q:'Why do Melbourne people carry umbrellas?',
   o:['Because it is always raining','Because they like umbrellas','Just in case the weather changes','To protect them from the sun'],
   a:2,t:'Reading Comprehension',e:'The passage says "just in case" — because Melbourne weather can change quickly.'},

  /* ── PASSAGE 6: Making a Bird Feeder ── */
  {id:'r21',
   p:'You can make a bird feeder from a plastic bottle. First, collect an empty clean bottle. Next, ask a grown-up to cut two holes on opposite sides near the bottom. Push a stick through both holes to make a perch for the birds. Fill the bottom of the bottle with birdseed. Hang the feeder from a tree branch with a piece of string. Wait and watch the birds come to eat!',
   q:'What type of text is this?',
   o:['A poem','An explanation','A set of instructions','A story'],a:2,t:'Text Type',
   e:'The passage gives step-by-step directions on how to make something — it is a set of instructions.'},
  {id:'r22',
   p:'You can make a bird feeder from a plastic bottle. First, collect an empty clean bottle. Next, ask a grown-up to cut two holes on opposite sides near the bottom. Push a stick through both holes to make a perch for the birds. Fill the bottom of the bottle with birdseed. Hang the feeder from a tree branch with a piece of string. Wait and watch the birds come to eat!',
   q:'What does the stick through the holes make?',
   o:['A handle','A lid','A perch for birds','A window'],a:2,t:'Reading Comprehension',
   e:'The passage says the stick makes "a perch for the birds."'},
  {id:'r23',
   p:'You can make a bird feeder from a plastic bottle. First, collect an empty clean bottle. Next, ask a grown-up to cut two holes on opposite sides near the bottom. Push a stick through both holes to make a perch for the birds. Fill the bottom of the bottle with birdseed. Hang the feeder from a tree branch with a piece of string. Wait and watch the birds come to eat!',
   q:'What is put inside the bottle?',
   o:['Water','Fruit','Birdseed','Bread'],a:2,t:'Reading Comprehension',
   e:'The passage says to "fill the bottom of the bottle with birdseed."'},
  {id:'r24',
   p:'You can make a bird feeder from a plastic bottle. First, collect an empty clean bottle. Next, ask a grown-up to cut two holes on opposite sides near the bottom. Push a stick through both holes to make a perch for the birds. Fill the bottom of the bottle with birdseed. Hang the feeder from a tree branch with a piece of string. Wait and watch the birds come to eat!',
   q:'Why do you need to ask a grown-up for help?',
   o:['To fill it with seeds','To hang it on the tree','To cut the holes in the bottle','To find the string'],
   a:2,t:'Reading Comprehension',e:'The passage says "ask a grown-up to cut two holes" — because cutting can be dangerous for children.'},

  /* ── PASSAGE 7: Wombats ── */
  {id:'r25',
   p:'Wombats are stocky Australian marsupials. They use their strong claws to dig burrows in the ground. Wombats are herbivores, which means they only eat plants such as grasses and roots. They are nocturnal — they sleep during the day and come out at night. A wombat\'s backwards-facing pouch keeps dirt out when the mother is digging. Baby wombats are called joeys.',
   q:'What does "nocturnal" mean in this passage?',
   o:['Sleeping all the time','Active during the day','Coming out at night','Living underground'],
   a:2,t:'Vocabulary',e:'The passage explains: "they sleep during the day and come out at night" — this is what nocturnal means.'},
  {id:'r26',
   p:'Wombats are stocky Australian marsupials. They use their strong claws to dig burrows in the ground. Wombats are herbivores, which means they only eat plants such as grasses and roots. They are nocturnal — they sleep during the day and come out at night. A wombat\'s backwards-facing pouch keeps dirt out when the mother is digging. Baby wombats are called joeys.',
   q:'Why does a wombat\'s pouch face backwards?',
   o:['So the joey can see where they are going','To keep dirt out while digging','Because wombats walk backwards','To help the joey climb out'],
   a:1,t:'Reading Comprehension',e:'The passage says the backwards pouch "keeps dirt out when the mother is digging."'},
  {id:'r27',
   p:'Wombats are stocky Australian marsupials. They use their strong claws to dig burrows in the ground. Wombats are herbivores, which means they only eat plants such as grasses and roots. They are nocturnal — they sleep during the day and come out at night. A wombat\'s backwards-facing pouch keeps dirt out when the mother is digging. Baby wombats are called joeys.',
   q:'What is a "herbivore"?',
   o:['An animal that eats only meat','An animal that eats plants and meat','An animal that eats only plants','An animal that does not eat'],
   a:2,t:'Vocabulary',e:'The passage defines herbivore as "only eat plants such as grasses and roots."'},
  {id:'r28',
   p:'Wombats are stocky Australian marsupials. They use their strong claws to dig burrows in the ground. Wombats are herbivores, which means they only eat plants such as grasses and roots. They are nocturnal — they sleep during the day and come out at night. A wombat\'s backwards-facing pouch keeps dirt out when the mother is digging. Baby wombats are called joeys.',
   q:'What body part do wombats use to dig?',
   o:['Their teeth','Their strong claws','Their nose','Their tail'],a:1,t:'Reading Comprehension',
   e:'The passage says wombats "use their strong claws to dig burrows."'},

  /* ── Standalone Vocabulary & Language Questions ── */
  {id:'r29',q:'Which word means "very happy"?',
   o:['Angry','Delighted','Worried','Tired'],a:1,t:'Vocabulary',e:'"Delighted" means very happy or pleased.'},
  {id:'r30',q:'Choose the word that means the opposite of "loud".',
   o:['Noisy','Soft','Quiet','Still'],a:2,t:'Vocabulary',e:'The opposite of loud is quiet.'},
  {id:'r31',q:'Which word is a synonym for "huge"?',
   o:['Tiny','Small','Enormous','Slim'],a:2,t:'Vocabulary',e:'Enormous is a synonym for huge — both mean very large.'},
  {id:'r32',q:'Which sentence has the correct meaning of the word "ancient"?',
   o:['The ancient rocket launched yesterday.','The ancient dinosaurs lived millions of years ago.','The ancient new phone is very fast.','The ancient baby smiled.'],
   a:1,t:'Vocabulary',e:'"Ancient" means very, very old — like dinosaurs from millions of years ago.'},
  {id:'r33',q:'What does "beneath" mean?',
   o:['On top of','Next to','Under','In front of'],a:2,t:'Vocabulary',
   e:'"Beneath" means under or below something.'},
  {id:'r34',q:'Choose the word that best completes the sentence: "The sun ___ brightly in the sky."',
   o:['roared','shone','splashed','whispered'],a:1,t:'Vocabulary',
   e:'"Shone" is the correct word — the sun shines light.'},
  {id:'r35',q:'Which word is a verb (doing word)?',
   o:['Beautiful','Garden','Running','Happy'],a:2,t:'Vocabulary',
   e:'"Running" is a verb — it describes an action or doing.'},
  {id:'r36',q:'Which sentence uses the word "cold" as an adjective (describing word)?',
   o:['She felt a cold.','The cold wind made her shiver.','Cold! shouted the teacher.','He colds easily.'],
   a:1,t:'Vocabulary',e:'In "the cold wind" — cold is describing the noun wind. It is an adjective.'},

  /* ── Sentence & Text Structure ── */
  {id:'r37',q:'Which sentence starts correctly?',
   o:['the dog ran fast.','The dog ran fast.','The dog Ran fast.','The Dog Ran Fast.'],
   a:1,t:'Sentences',e:'Sentences begin with a capital letter. Only the first word (and proper nouns) is capitalised.'},
  {id:'r38',q:'Which word BEST replaces the underlined word: "The baby was very small."',
   o:['giant','tiny','large','tall'],a:1,t:'Vocabulary',e:'"Tiny" is a synonym for very small — it fits perfectly.'},
  {id:'r39',q:'Which sentence is a question?',
   o:['Come here please.','What a lovely day!','Where is my bag?','The cat sat on the mat.'],
   a:2,t:'Sentences',e:'Questions ask something and end with a question mark. "Where is my bag?" is a question.'},
  {id:'r40',q:'Read this sentence: "After eating his lunch, Jake went to play in the park." What did Jake do first?',
   o:['Went to the park','Played cricket','Ate his lunch','Ran home'],a:2,t:'Reading Comprehension',
   e:'The sentence says "after eating his lunch" — so eating lunch happened first.'},
  {id:'r41',q:'Which sentence is a statement?',
   o:['Is it raining?','Look out!','The train arrives at 3 pm.','Stop running!'],
   a:2,t:'Sentences',e:'A statement gives information. "The train arrives at 3 pm" is a statement.'},
  {id:'r42',q:'A story has a beginning, a middle and an ___.',
   o:['answer','ending','introduction','question'],a:1,t:'Text Structure',
   e:'Stories have a beginning, middle, and ending.'},
  {id:'r43',q:'Which word tells us WHEN something happened?',
   o:['slowly','quietly','yesterday','carefully'],a:2,t:'Vocabulary',
   e:'"Yesterday" is a time word — it tells us when something happened.'},
  {id:'r44',q:'Choose the connecting word that fits: "I wanted to go swimming ___ it was raining."',
   o:['and','so','but','because'],a:2,t:'Sentences',
   e:'"But" shows contrast — wanting to swim but it was raining.'},

  /* ── Poetry & Other Text Types ── */
  {id:'r45',
   p:'Roses are red,\nViolets are blue,\nKangaroos hop,\nAnd wombats do too!',
   q:'What type of text is this?',
   o:['A letter','A poem','An instruction','A report'],a:1,t:'Text Type',
   e:'The text uses rhyme and short lines — it is a poem.'},
  {id:'r46',
   p:'Roses are red,\nViolets are blue,\nKangaroos hop,\nAnd wombats do too!',
   q:'Which two animals are mentioned in the poem?',
   o:['Koalas and wombats','Kangaroos and koalas','Kangaroos and wombats','Wallabies and wombats'],
   a:2,t:'Reading Comprehension',e:'The poem mentions kangaroos and wombats.'},
  {id:'r47',
   p:'Roses are red,\nViolets are blue,\nKangaroos hop,\nAnd wombats do too!',
   q:'In the poem, which word rhymes with "blue"?',
   o:['hop','red','too','roses'],a:2,t:'Reading Comprehension',
   e:'"Too" rhymes with "blue" — they have the same ending sound.'},

  /* ── PASSAGE 8: Zara at the Farmers Market ── */
  {id:'r48',
   p:'Every Saturday, Zara and her mum go to the farmers market in Melbourne. They buy fresh fruit and vegetables from local farmers. Zara\'s favourite stall sells honey. The beekeeper explains how bees collect nectar from flowers and turn it into honey. Zara buys a small jar to take home. She uses the honey to make sweet toast for breakfast.',
   q:'When do Zara and her mum go to the market?',
   o:['Every Friday','Every Saturday','Every Sunday','Every Monday'],a:1,t:'Reading Comprehension',
   e:'The passage says "Every Saturday, Zara and her mum go to the farmers market."'},
  {id:'r49',
   p:'Every Saturday, Zara and her mum go to the farmers market in Melbourne. They buy fresh fruit and vegetables from local farmers. Zara\'s favourite stall sells honey. The beekeeper explains how bees collect nectar from flowers and turn it into honey. Zara buys a small jar to take home. She uses the honey to make sweet toast for breakfast.',
   q:'What is Zara\'s favourite stall at the market?',
   o:['The fruit stall','The vegetable stall','The honey stall','The bread stall'],a:2,t:'Reading Comprehension',
   e:'The passage says "Zara\'s favourite stall sells honey."'},
  {id:'r50',
   p:'Every Saturday, Zara and her mum go to the farmers market in Melbourne. They buy fresh fruit and vegetables from local farmers. Zara\'s favourite stall sells honey. The beekeeper explains how bees collect nectar from flowers and turn it into honey. Zara buys a small jar to take home. She uses the honey to make sweet toast for breakfast.',
   q:'How do bees make honey, according to the passage?',
   o:['They mix sugar and water','They collect nectar from flowers','They get it from other insects','They make it from leaves'],
   a:1,t:'Reading Comprehension',e:'The passage says bees "collect nectar from flowers and turn it into honey."'},
  {id:'r51',
   p:'Every Saturday, Zara and her mum go to the farmers market in Melbourne. They buy fresh fruit and vegetables from local farmers. Zara\'s favourite stall sells honey. The beekeeper explains how bees collect nectar from flowers and turn it into honey. Zara buys a small jar to take home. She uses the honey to make sweet toast for breakfast.',
   q:'What does Zara use the honey for at home?',
   o:['Making a cake','Sweetening her drink','Making toast for breakfast','Cooking dinner'],
   a:2,t:'Reading Comprehension',e:'The passage says "She uses the honey to make sweet toast for breakfast."'},

  /* ── More Standalone Reading / Vocabulary ── */
  {id:'r52',q:'Which word tells you HOW someone moved? "She walked ___."',
   o:['quickly','tomorrow','school','blue'],a:0,t:'Vocabulary',
   e:'"Quickly" is an adverb — it tells us how she walked.'},
  {id:'r53',q:'Which of these is the main idea of a story about a lost puppy that finds its way home?',
   o:['Puppies like to run around.','A puppy gets lost and then finds its way back home.','Dogs need food and water.','Puppies are very cute.'],
   a:1,t:'Reading Comprehension',e:'The main idea is the most important point: the puppy gets lost and finds its way home.'},
  {id:'r54',q:'What punctuation mark ends an exclamation?',
   o:['.','?','!',','],a:2,t:'Language Conventions',e:'An exclamation mark (!) shows strong feeling or surprise.'},
  {id:'r55',q:'A book about one person\'s life, written by that person, is called a(n):',
   o:['dictionary','autobiography','recipe book','atlas'],a:1,t:'Text Type',
   e:'An autobiography is a book about your own life written by yourself.'},
  {id:'r56',q:'Which word is a noun (naming word)?',
   o:['Jump','Soft','Quickly','River'],a:3,t:'Vocabulary',
   e:'"River" is a noun — it names a place or thing.'},
  {id:'r57',q:'Read: "The enormous elephant splashed in the muddy river." Which word tells us about the elephant?',
   o:['splashed','muddy','enormous','river'],a:2,t:'Vocabulary',
   e:'"Enormous" is an adjective describing the elephant.'},
  {id:'r58',q:'Choose the best title for a story that begins: "One morning, a tiny frog decided to cross the busy highway..."',
   o:['My Pet Frog','The Frog\'s Big Journey','All About Frogs','Melbourne\'s Weather'],
   a:1,t:'Reading Comprehension',e:'"The Frog\'s Big Journey" best matches the story — it is about the frog\'s adventure crossing the highway.'},
  {id:'r59',q:'Which two words are antonyms (opposites)?',
   o:['big / large','happy / joyful','fast / slow','dark / gloomy'],a:2,t:'Vocabulary',
   e:'"Fast" and "slow" are antonyms — they mean opposite things.'},
  {id:'r60',q:'Which sentence uses "their" correctly?',
   o:['Their going to the park.','The children left there bags behind.','The dogs wagged their tails.','There is two cats over their.'],
   a:2,t:'Language Conventions',e:'"Their" shows belonging — "their tails" means the tails belonging to the dogs.'},
  {id:'r61',q:'Read: "First we mixed the flour. Then we added eggs. Finally we baked the cake." What word tells us the last step?',
   o:['First','Then','Finally','Next'],a:2,t:'Reading Comprehension',
   e:'"Finally" signals the last step in a sequence.'},
  {id:'r62',q:'Which sentence gives a fact rather than an opinion?',
   o:['Cats are the best pets.','Dogs are nicer than cats.','Australia has many unique animals.','Swimming is more fun than reading.'],
   a:2,t:'Reading Comprehension',e:'"Australia has many unique animals" is a verifiable fact. The others are opinions.'}
];
